"""Bot-authored UI strings, keyed for future per-chat localization."""

STRINGS: dict[str, dict[str, str]] = {
    "ru": {
        'bridge_file_send_watcher_loop_1': 'Отклонено: повреждённый запрос отправки файла.',
        'bridge_file_send_watcher_loop_2': 'Отклонено: некорректный Telegram chat_id.',
        'bridge_file_send_watcher_loop_3': 'Отклонено: Telegram ID отсутствует в whitelist Claude bridge.',
        'bridge_file_send_watcher_loop_4': 'Отклонено: некорректный путь или подпись.',
        'bridge_file_send_watcher_loop_5': 'Отклонено: подпись длиннее лимита Telegram.',
        'bridge_file_send_watcher_loop_6': 'Отклонено: файл должен быть обычным файлом из CLAUDE_TELEGRAM_OUTBOX.',
        'bridge_file_send_watcher_loop_7': 'Отклонено: файл больше {value0} байт.',
        'bridge_file_send_watcher_loop_8': 'Файл «{value0}» отправлен в Telegram.',
        'bridge_file_send_watcher_loop_9': 'Telegram не принял файл: ',
        'bridge_restart_watcher_loop_1': '❌ SERVICE_NAME не задан — перезапуск невозможен.',
        'bridge_restart_watcher_loop_2': '🔄 Идёт перезагрузка, ничего не делайте пока процесс не будет завершён...',
        'bridge_restart_watcher_loop_3': 'код {value0}',
        'bridge_restart_watcher_loop_4': '❌ Перезапуск не выполнен: {value0}',
        'bridge_external_request_watcher_loop_1': 'Повреждённый запрос делегации.',
        'bridge_external_request_watcher_loop_2': 'Пустой текст задачи.',
        'bridge_cross_delegate_watcher_loop_1': 'Отклонено: повреждённый формат запроса делегации.',
        'bridge_cross_delegate_watcher_loop_2': 'Отклонено: пустой текст задачи.',
        'bridge_cross_delegate_watcher_loop_3': 'Отклонено: этот Telegram ID отсутствует в whitelist Claude bridge.',
        'bridge_cross_delegate_watcher_loop_4': 'Отклонено: Claude-аккаунт для этого Telegram ID не готов. Сначала заверши /login в Claude bridge.',
        'bridge_cross_delegate_watcher_loop_5': 'Принято: Claude bridge запустил задачу. Результат придёт в этот же Telegram-чат от Claude bridge.',
        'bridge_cross_delegate_watcher_loop_6': 'Отклонено: уже выполняется предыдущая делегированная задача.',
        'bridge_process_message_1': '⏹ Прерываю текущий запрос...',
        'bridge_process_message_2': 'Сейчас ничего не выполняется.',
        'bridge_process_message_3': 'Нет заблокированного действия для approve.',
        'bridge_process_message_4': 'Заблокированное действие относится к прошлой сессии — повторять его в текущей не буду.',
        'bridge_process_message_5': 'Bypass включён для этой сессии насовсем. Повторяю...',
        'bridge_process_message_6': 'Разрешаю один раз. Повторяю...',
        'bridge_process_message_7': 'Отклонено.',
        'bridge_process_message_8': 'Нечего отклонять.',
        'bridge_process_message_9': 'Голосовые сообщения не распознаются: на этой установке нет faster-whisper (см. setup.sh). Напиши текстом.',
        'bridge_process_message_10': '📥 Загружаю вложение…',
        'bridge_process_message_11': 'Не удалось распознать голосовое сообщение.',
        'bridge_process_message_12': 'Ошибка моста:\n```\n{value0}\n```',
        'bridge_main_1': '✅ Перезагрузка окончена, бот готов к работе.',
        'handlers_model_from_spec_1': 'Неизвестное семейство «{value0}». Доступно: {value1}, default',
        'handlers_model_from_spec_2': 'У {value0} нет версии {value1}.',
        'handlers_resolve_effort_spec_1': 'модели по умолчанию CLI',
        'handlers_resolve_effort_spec_2': 'Мощность «{value0}» недоступна для {value1}.',
        'handlers_effort_label_1': 'не поддерживается',
        'handlers_effort_label_2': 'по умолчанию',
        'handlers_render_model_picker_1': '🧠 Модели Claude:',
        'handlers_render_model_picker_2': '{value0} По умолчанию CLI — `/model default`',
        'handlers_render_model_picker_3': '⚡ Мощность: {value0}. Выбрать: /effort',
        'handlers_render_effort_picker_1': '⚡ {value0} не поддерживает настройку мощности.',
        'handlers_render_effort_picker_2': 'по умолчанию CLI',
        'handlers_render_effort_picker_3': '⚡ Мощность модели {value0}:',
        'handlers_render_effort_picker_4': '{value0} По умолчанию CLI — `/effort default`',
        'handlers_telegram_bot_api_unit_1': 'Некорректное имя юнита локального Bot API.',
        'handlers_repair_local_bot_api_service_1': '⚠️ Локальный сервер настроен, но его systemd-юнит не установлен. Не запускаю установку из бота; прогони scripts/install-local-bot-api.sh вручную.',
        'handlers_repair_local_bot_api_service_2': '⚠️ Не смог перезапустить локальный сервер: {value0}',
        'handlers_repair_local_bot_api_service_3': 'команда завершилась с ошибкой',
        'handlers_repair_local_bot_api_service_4': '🔧 Локальный сервер был неактивен; отправил рестарт юнита.',
        'handlers_write_telegram_api_url_1': 'Установщик вернул недопустимый адрес локального сервера',
        'handlers_write_telegram_api_url_2': 'Не найден env-файл бриджа: {value0}',
        'handlers_finish_local_bot_api_setup_1': '⚠️ Не удалось включить локальный сервер: {value0}',
        'handlers_finish_local_bot_api_setup_2': '✅ Локальный сервер включён. Перезапускаю бота…',
        'handlers_run_local_bot_api_install_1': '⏳ Проверяю зависимости сборки…',
        'handlers_run_local_bot_api_install_2': '⏳ Собираю локальный Bot API сервер (это может занять несколько минут)…',
        'handlers_run_local_bot_api_install_3': '⏳ Устанавливаю локальный Bot API сервер…',
        'handlers_run_local_bot_api_install_4': '⏳ Локальный сервер готов, переключаю бота…',
        'handlers_run_local_bot_api_install_5': '⏳ Готовлю локальный Bot API сервер…',
        'handlers_run_local_bot_api_install_6': '⏳ Использую уже настроенный локальный сервер…',
        'handlers_run_local_bot_api_install_7': 'установщик завершился с ошибкой',
        'handlers_run_local_bot_api_install_8': 'установщик не сообщил адрес локального сервера',
        'handlers_run_local_bot_api_install_9': 'переключатель завершился с ошибкой',
        'handlers_start_local_bot_api_install_1': 'не хватает зависимостей сборки; прогони scripts/install-local-bot-api.sh вручную.',
        'handlers_handle_local_bot_api_setup_reply_1': 'Установка локального Bot API уже идёт, дождись её завершения.',
        'handlers_handle_local_bot_api_setup_reply_2': 'Пришли api_id.',
        'handlers_handle_local_bot_api_setup_reply_3': 'Ладно. Перезапускаю бота, чтобы обновление вступило в силу…',
        'handlers_handle_local_bot_api_setup_reply_4': 'Пришли api_id (только цифры).',
        'handlers_handle_local_bot_api_setup_reply_5': 'Пришли api_hash.',
        'handlers_handle_local_bot_api_setup_reply_6': 'Пришли непустой api_hash.',
        'handlers_send_persona_1': 'Текущая персона',
        'handlers_handle_persona_reply_1': 'Файл персоны должен быть текстовым UTF-8 Markdown-файлом.',
        'handlers_handle_persona_reply_2': 'Не удалось прочитать файл персоны: {value0}',
        'handlers_handle_persona_reply_3': 'Пришли текст персоны или UTF-8 Markdown-файл ответом на сообщение.',
        'handlers_handle_persona_reply_4': 'Пустая персона не сохранена.',
        'handlers_handle_persona_reply_5': '✅ Персона обновлена.',
        'handlers_handle_command_1': 'Персона доступна только владельцу в личном чате.',
        'handlers_handle_command_2': '✅ Персона сброшена к шаблону по умолчанию.',
        'handlers_handle_command_3': 'Использование: /persona или /persona reset',
        'handlers_handle_command_4': 'Начинаю новую сессию.',
        'handlers_handle_command_5': 'Сессий не найдено.',
        'handlers_handle_command_6': 'Последние сессии:',
        'handlers_handle_command_7': ' ← текущая',
        'handlers_handle_command_8': 'Использование: /resume <session_id или префикс>',
        'handlers_handle_command_9': 'Сессия {value0} не найдена.',
        'handlers_handle_command_10': 'Префикс {value0} подходит к нескольким сессиям, уточни id:',
        'handlers_handle_command_11': '…и ещё {value0}',
        'handlers_handle_command_12': 'Продолжаю {value0}сессию {value1}.',
        'handlers_handle_command_13': 'делегированную ',
        'handlers_handle_command_14': '`{value0}`  •  Model: {value1}  •  Мощность: {value2}',
        'handlers_handle_command_15': 'нет активной',
        'handlers_handle_command_16': '(~${value0:.4f} эквивалент по API-тарифу)',
        'handlers_handle_command_17': 'Модель «{value0}» недоступна.\n\n{value1}',
        'handlers_handle_command_18': 'По умолчанию CLI',
        'handlers_handle_command_19': '🧠 Модель: {value0}',
        'handlers_handle_command_20': 'Мощность: {value0}',
        'handlers_handle_command_21': 'Выбранная мощность не поддерживается новой моделью и сброшена.',
        'handlers_handle_command_22': 'Мощность «{value0}» недоступна для {value1}.\n\n{value2}',
        'handlers_handle_command_23': '⚡ Мощность {value0}: {value1}',
        'handlers_handle_command_24': 'Текущий режим: `{value0}`\nДоступно: {value1}\n\nbypass — без подтверждений (по умолчанию)\ndefault — каждое опасное действие требует /approve\nacceptEdits — правки файлов авто, остальное требует /approve\nplan — только чтение, ничего не меняет',
        'handlers_handle_command_25': 'Неизвестный режим. Доступно: {value0}',
        'handlers_handle_command_26': 'Режим переключён на {value0}.',
        'handlers_handle_command_27': 'Текущий workspace: `{value0}`\nИспользование: /workspace <путь>, /workspace default',
        'handlers_handle_command_28': 'Workspace сброшен на {value0}.',
        'handlers_handle_command_29': 'Директория не существует: `{value0}`',
        'handlers_handle_command_30': 'Workspace переключён на `{value0}`.',
        'handlers_handle_command_31': 'да, выполняется запрос (можно /stop)',
        'handlers_handle_command_32': 'нет',
        'handlers_handle_command_33': 'не начат',
        'handlers_handle_command_34': 'ℹ️ **Статус**',
        'handlers_handle_command_35': 'Сессия: `{value0}`',
        'handlers_handle_command_36': 'Модель: `{value0}` · Мощность: `{value1}`',
        'handlers_handle_command_37': 'Режим: `{value0}`',
        'handlers_handle_command_38': 'Занят: {value0}',
        'handlers_handle_command_39': 'Аккаунт Claude: {value0}',
        'handlers_handle_command_40': 'Использование: /login или /login delegate',
        'handlers_handle_command_41': 'Начинаю переподключение аккаунта Claude...',
        'handlers_handle_command_42': 'Перезапуск доступен только владельцу.',
        'handlers_handle_command_43': 'SERVICE_NAME не задан в systemd-юните — автоперезапуск недоступен.',
        'handlers_handle_command_44': '🔁 Перезапуск запланирован — выполнится, как только текущие запросы завершатся.',
        'handlers_handle_command_45': 'Обновление доступно только владельцу.',
        'handlers_handle_command_46': 'Настройка локального Bot API уже начата; закончи текущий диалог.',
        'handlers_handle_command_47': '⬇️ Обновляю из git...',
        'handlers_handle_command_48': '❌ Не смог запустить update.sh: {value0}',
        'handlers_handle_command_49': '❌ Обновление не удалось:\n```\n{value0}\n```',
        'handlers_handle_command_50': 'обновлено',
        'handlers_handle_command_51': 'Включить приём файлов до 2 ГБ через локальный Bot API сервер? Да/Нет',
        'handlers_handle_command_52': ' Перезапуск — как только текущие запросы завершатся.',
        'handlers_handle_command_53': ' Перезапуск — между ходами.',
        'handlers_spawn_turn_1': 'Уже выполняю предыдущий запрос. Дождись ответа или используй /stop.',
        'handlers_start_delegate_turn_1': 'Уже выполняю предыдущую делегированную задачу.',
        'handlers_start_delegate_turn_2': 'Делегированный аккаунт Claude не подключён. Используй /login delegate.',
        'handlers_start_delegate_turn_3': 'Нельзя использовать --env вместе с --resume.',
        'handlers_start_delegate_turn_4': 'Нельзя продолжить эту делегацию: resume_session_id не совпадает с последней сессией делегатора.',
        'handlers_start_delegate_turn_5': 'Делегированная задача не запущена.',
        'handlers_send_whitelist_prompt_1': 'Вы не внесены в белый список.\nВаш Telegram ID: `{value0}`\n\nДобавьте его в конфиг через запятую и нажмите на кнопку снизу:',
        'handlers_send_whitelist_prompt_2': 'Готово ✅',
        'handlers_reader_1': '1. Нажми на кнопку ниже\n2. Войди в свой аккаунт Claude\n3. Пришли мне сюда код, который дадут после входа\n\nПримечание: для входа нужна подписка Pro или выше.',
        'handlers_reader_2': '🔗 Войти в Claude',
        'handlers_reader_3': '❌ Не удалось запустить вход Claude. Попробуй /login ещё раз.',
        'handlers_feed_login_code_1': 'Не смог передать код процессу логина. Попробуй /login заново.',
        'handlers_check_1': '✅ Делегированный аккаунт Claude подключён.',
        'handlers_check_2': '✅ Аккаунт подключён. Можно пользоваться ботом.',
        'handlers_check_3': '✅ Аккаунт подключён.\n\nКак к тебе обращаться?',
        'handlers_check_4': 'Не удалось подтвердить вход. Проверь код и попробуй /login ещё раз.',
        'handlers_handle_onboarding_1': 'Перезапускаю вход делегированного Claude — сейчас пришлю новую ссылку.',
        'handlers_handle_onboarding_2': 'Жду код авторизации (пришли его текстом, без команд).',
        'handlers_handle_onboarding_3': 'Перезапускаю вход Claude — сейчас пришлю новую ссылку.',
        'handlers_handle_onboarding_4': '✅ Готово. Можно пользоваться ботом.',
        'handlers_handle_onboarding_5': 'Ты в списке — начинаю подключение твоего аккаунта Claude...',
        'handlers_handle_callback_query_1': 'Ещё не добавлен в список.',
        'handlers_handle_callback_query_2': 'Принято!',
        'handlers_handle_callback_query_3': 'Аккаунт уже подключён.',
        'chat_process_finish_delivery_1': '⚠️ Ответ не удалось доставить в Telegram:\n\n',
        'chat_process_deliver_pending_final_1': '⚠️ Telegram пока не принял ответ, доставка повторяется:\n\n',
        'chat_process_format_turn_footer_1': 'Токены: {value0}',
        'chat_process_format_turn_footer_2': 'Твой session id (до делегации): `{value0}`. Продолжить делегированную: `/resume {value1}`',
        'chat_process_format_turn_footer_3': 'Продолжить делегированную сессию: `/resume {value0}`',
        'chat_process_flush_draft_1': 'Думаю',
        'chat_process_compact_draft_watchdog_1': '🗜 Сжимаю контекст сессии... ({value0}с, это может занять несколько минут)',
        'chat_process_deliver_turn_result_1': '…и ещё {value0} шагов выше…',
        'chat_process_deliver_turn_result_2': '<details><summary>🔧 Процесс ({value0})</summary>\n{value1}\n</details>',
        'chat_process_deliver_turn_result_3': '⏹ Ход прерван — процесс завершился, не дождавшись ответа.',
        'chat_process_deliver_turn_result_4': '(нет ответа — смотри процесс выше)',
        'chat_process_deliver_turn_result_5': '(пусто)',
        'chat_process_deliver_turn_result_6': '🚫 **Заблокировано** (нужно разрешение):',
        'chat_process_deliver_turn_result_7': '/approve — повторить один раз с bypass',
        'chat_process_deliver_turn_result_8': '/approve session — включить bypass насовсем для этой сессии',
        'chat_process_deliver_turn_result_9': '/deny — оставить как есть',
        'chat_process_chat_reader_loop_1': '🗜 Сжимаю контекст сессии...',
        'chat_process_chat_reader_loop_2': 'неизвестная ошибка',
        'chat_process_chat_reader_loop_3': '🗜 Не удалось сжать контекст: {value0}',
        'chat_process_chat_reader_loop_4': '🗜 Контекст сессии сжат.',
        'chat_process_chat_reader_loop_5': '{value0} (пусто)',
        'chat_process_chat_reader_loop_6': 'Ошибка',
        'chat_process_chat_reader_loop_7': 'Результат',
        'telegram_api_send_attachment_1': 'Файл `{value0}` слишком большой для отправки ({value1} байт).',
        'telegram_api_send_attachment_2': 'Не удалось отправить `{value0}`: {value1}',
        'telegram_api_download_error_from_exception_1': 'Файл не скачан: Telegram слишком долго готовил файл. Попробуй ещё раз или дай ссылку.',
        'telegram_api_download_error_from_exception_2': 'Файл не скачан: нет доступа к файлу локального Bot API.',
        'telegram_api_download_error_from_exception_3': 'Файл не скачан: ошибка связи с Telegram. Попробуй ещё раз или дай ссылку.',
        'telegram_api_download_error_from_exception_4': 'Файл не скачан: Telegram не дал получить файл. Попробуй ещё раз или дай ссылку.',
        'telegram_api_get_file_error_1': 'Файл не скачан: размер превышает облачный лимит Telegram 20 МБ. Включи локальный Bot API или дай ссылку.',
        'telegram_api_get_file_error_2': 'Файл не скачан: Telegram отказал в выдаче файла. Отправь его снова или дай ссылку.',
        'telegram_api_download_telegram_file_1': 'Файл не скачан: Telegram не вернул путь к файлу. Попробуй ещё раз или дай ссылку.',
        'telegram_api_download_telegram_file_2': 'Файл не скачан: локальный Bot API больше не видит этот файл. Отправь его снова или дай ссылку.',
        'telegram_api_download_telegram_file_3': 'Файл не скачан: путь локального Bot API не является доступным файлом.',
        'telegram_api_download_telegram_file_4': 'Файл не скачан: размер превышает разрешённый лимит.',
        'runtime_module_1': '🔄 Бот перезапускается — повтори сообщение через минуту.',
        'state_store_add_usage_1': '⚠️ Стоимость этой сессии по API-эквиваленту выросла ещё на ${value0:.0f} (всего ~${value1:.2f}). Есть смысл сделать /compact или начать заново через /new.',
        'state_store_fetch_account_limits_1': '(не удалось получить лимиты: {value0})',
        'state_store_fetch_account_limits_2': '(нет данных)',
    },
}


def t(key, lang="ru", **kwargs) -> str:
    template = STRINGS.get(lang, {}).get(key)
    if template is None:
        template = STRINGS["ru"][key]
    return template.format(**kwargs)
