"""Localized bot-authored UI strings."""

import contextvars


current_language: contextvars.ContextVar[str] = contextvars.ContextVar(
    "current_language", default="ru",
)

STRINGS: dict[str, dict[str, str]] = {
    "ru": {
        'bridge_file_send_watcher_loop_1': 'Отклонено: повреждённый запрос отправки файла.',
        'bridge_file_send_watcher_loop_2': 'Отклонено: некорректный Telegram chat_id.',
        'bridge_file_send_watcher_loop_3': 'Отклонено: Telegram ID отсутствует в whitelist Claude bridge.',
        'bridge_file_send_watcher_loop_4': 'Отклонено: некорректный путь или подпись.',
        'bridge_file_send_watcher_loop_5': 'Отклонено: подпись длиннее лимита Telegram.',
        'bridge_file_send_watcher_loop_6': 'Отклонено: файл должен быть обычным файлом из CLAUDE_TELEGRAM_OUTBOX.',
        'bridge_file_send_watcher_loop_7': 'Отклонено: файл больше {value0} байт.',
        'bridge_file_send_watcher_loop_8': 'Файл «{value0}» отправлен в Telegram.',
        'bridge_file_send_watcher_loop_9': 'Telegram не принял файл: ',
        'bridge_restart_watcher_loop_1': '❌ SERVICE_NAME не задан — перезапуск невозможен.',
        'bridge_restart_watcher_loop_2': '🔄 Идёт перезагрузка, ничего не делайте пока процесс не будет завершён...',
        'bridge_restart_watcher_loop_3': 'код {value0}',
        'bridge_restart_watcher_loop_4': '❌ Перезапуск не выполнен: {value0}',
        'bridge_external_request_watcher_loop_1': 'Повреждённый запрос делегации.',
        'bridge_external_request_watcher_loop_2': 'Пустой текст задачи.',
        'bridge_cross_delegate_watcher_loop_1': 'Отклонено: повреждённый формат запроса делегации.',
        'bridge_cross_delegate_watcher_loop_2': 'Отклонено: пустой текст задачи.',
        'bridge_cross_delegate_watcher_loop_3': 'Отклонено: этот Telegram ID отсутствует в whitelist Claude bridge.',
        'bridge_cross_delegate_watcher_loop_4': 'Отклонено: Claude-аккаунт для этого Telegram ID не готов. Сначала заверши /login в Claude bridge.',
        'bridge_cross_delegate_watcher_loop_5': 'Принято: Claude bridge запустил задачу. Результат придёт в этот же Telegram-чат от Claude bridge.',
        'bridge_cross_delegate_watcher_loop_6': 'Отклонено: уже выполняется предыдущая делегированная задача.',
        'bridge_process_message_1': '⏹ Прерываю текущий запрос...',
        'bridge_process_message_2': 'Сейчас ничего не выполняется.',
        'bridge_process_message_3': 'Нет заблокированного действия для approve.',
        'bridge_process_message_4': 'Заблокированное действие относится к прошлой сессии — повторять его в текущей не буду.',
        'bridge_process_message_5': 'Bypass включён для этой сессии насовсем. Повторяю...',
        'bridge_process_message_6': 'Разрешаю один раз. Повторяю...',
        'bridge_process_message_7': 'Отклонено.',
        'bridge_process_message_8': 'Нечего отклонять.',
        'bridge_process_message_9': 'Голосовые сообщения не распознаются: на этой установке нет faster-whisper (см. setup.sh). Напиши текстом.',
        'bridge_process_message_10': '📥 Загружаю вложение…',
        'bridge_process_message_11': 'Не удалось распознать голосовое сообщение.',
        'bridge_process_message_12': 'Ошибка моста:\n```\n{value0}\n```',
        'bridge_main_1': '✅ Перезагрузка окончена, бот готов к работе.',
        'handlers_model_from_spec_1': 'Неизвестное семейство «{value0}». Доступно: {value1}, default',
        'handlers_model_from_spec_2': 'У {value0} нет версии {value1}.',
        'handlers_resolve_effort_spec_1': 'модели по умолчанию CLI',
        'handlers_resolve_effort_spec_2': 'Мощность «{value0}» недоступна для {value1}.',
        'handlers_effort_label_1': 'не поддерживается',
        'handlers_effort_label_2': 'по умолчанию',
        'handlers_render_model_picker_1': '🧠 Модели Claude:',
        'handlers_render_model_picker_2': '{value0} По умолчанию CLI — `/model default`',
        'handlers_render_model_picker_3': '⚡ Мощность: {value0}. Выбрать: /effort',
        'handlers_render_effort_picker_1': '⚡ {value0} не поддерживает настройку мощности.',
        'handlers_render_effort_picker_2': 'по умолчанию CLI',
        'handlers_render_effort_picker_3': '⚡ Мощность модели {value0}:',
        'handlers_render_effort_picker_4': '{value0} По умолчанию CLI — `/effort default`',
        'handlers_telegram_bot_api_unit_1': 'Некорректное имя юнита локального Bot API.',
        'handlers_repair_local_bot_api_service_1': '⚠️ Локальный сервер настроен, но его systemd-юнит не установлен. Не запускаю установку из бота; прогони scripts/install-local-bot-api.sh вручную.',
        'handlers_repair_local_bot_api_service_2': '⚠️ Не смог перезапустить локальный сервер: {value0}',
        'handlers_repair_local_bot_api_service_3': 'команда завершилась с ошибкой',
        'handlers_repair_local_bot_api_service_4': '🔧 Локальный сервер был неактивен; отправил рестарт юнита.',
        'handlers_write_telegram_api_url_1': 'Установщик вернул недопустимый адрес локального сервера',
        'handlers_write_telegram_api_url_2': 'Не найден env-файл бриджа: {value0}',
        'handlers_finish_local_bot_api_setup_1': '⚠️ Не удалось включить локальный сервер: {value0}',
        'handlers_finish_local_bot_api_setup_2': '✅ Локальный сервер включён. Перезапускаю бота…',
        'handlers_run_local_bot_api_install_1': '⏳ Проверяю зависимости сборки…',
        'handlers_run_local_bot_api_install_2': '⏳ Собираю локальный Bot API сервер (это может занять несколько минут)…',
        'handlers_run_local_bot_api_install_3': '⏳ Устанавливаю локальный Bot API сервер…',
        'handlers_run_local_bot_api_install_4': '⏳ Локальный сервер готов, переключаю бота…',
        'handlers_run_local_bot_api_install_5': '⏳ Готовлю локальный Bot API сервер…',
        'handlers_run_local_bot_api_install_6': '⏳ Использую уже настроенный локальный сервер…',
        'handlers_run_local_bot_api_install_7': 'установщик завершился с ошибкой',
        'handlers_run_local_bot_api_install_8': 'установщик не сообщил адрес локального сервера',
        'handlers_run_local_bot_api_install_9': 'переключатель завершился с ошибкой',
        'handlers_start_local_bot_api_install_1': 'не хватает зависимостей сборки; прогони scripts/install-local-bot-api.sh вручную.',
        'handlers_handle_local_bot_api_setup_reply_1': 'Установка локального Bot API уже идёт, дождись её завершения.',
        'handlers_handle_local_bot_api_setup_reply_2': 'Пришли api_id.',
        'handlers_handle_local_bot_api_setup_reply_3': 'Ладно. Перезапускаю бота, чтобы обновление вступило в силу…',
        'handlers_handle_local_bot_api_setup_reply_4': 'Пришли api_id (только цифры).',
        'handlers_handle_local_bot_api_setup_reply_5': 'Пришли api_hash.',
        'handlers_handle_local_bot_api_setup_reply_6': 'Пришли непустой api_hash.',
        'handlers_send_persona_1': 'Текущая персона',
        'handlers_handle_persona_reply_1': 'Файл персоны должен быть текстовым UTF-8 Markdown-файлом.',
        'handlers_handle_persona_reply_2': 'Не удалось прочитать файл персоны: {value0}',
        'handlers_handle_persona_reply_3': 'Пришли текст персоны или UTF-8 Markdown-файл ответом на сообщение.',
        'handlers_handle_persona_reply_4': 'Пустая персона не сохранена.',
        'handlers_handle_persona_reply_5': '✅ Персона обновлена.',
        'handlers_handle_command_1': 'Персона доступна только владельцу в личном чате.',
        'handlers_handle_command_2': '✅ Персона сброшена к шаблону по умолчанию.',
        'handlers_handle_command_3': 'Использование: /persona или /persona reset',
        'handlers_handle_command_4': 'Начинаю новую сессию.',
        'handlers_handle_command_5': 'Сессий не найдено.',
        'handlers_handle_command_6': 'Последние сессии:',
        'handlers_handle_command_7': ' ← текущая',
        'handlers_handle_command_8': 'Использование: /resume <session_id или префикс>',
        'handlers_handle_command_9': 'Сессия {value0} не найдена.',
        'handlers_handle_command_10': 'Префикс {value0} подходит к нескольким сессиям, уточни id:',
        'handlers_handle_command_11': '…и ещё {value0}',
        'handlers_handle_command_12': 'Продолжаю {value0}сессию {value1}.',
        'handlers_handle_command_13': 'делегированную ',
        'handlers_handle_command_14': '`{value0}`  •  Model: {value1}  •  Мощность: {value2}',
        'handlers_handle_command_15': 'нет активной',
        'handlers_handle_command_16': '(~${value0:.4f} эквивалент по API-тарифу)',
        'handlers_handle_command_17': 'Модель «{value0}» недоступна.\n\n{value1}',
        'handlers_handle_command_18': 'По умолчанию CLI',
        'handlers_handle_command_19': '🧠 Модель: {value0}',
        'handlers_handle_command_20': 'Мощность: {value0}',
        'handlers_handle_command_21': 'Выбранная мощность не поддерживается новой моделью и сброшена.',
        'handlers_handle_command_22': 'Мощность «{value0}» недоступна для {value1}.\n\n{value2}',
        'handlers_handle_command_23': '⚡ Мощность {value0}: {value1}',
        'handlers_handle_command_24': 'Текущий режим: `{value0}`\nДоступно: {value1}\n\nbypass — без подтверждений (по умолчанию)\ndefault — каждое опасное действие требует /approve\nacceptEdits — правки файлов авто, остальное требует /approve\nplan — только чтение, ничего не меняет',
        'handlers_handle_command_25': 'Неизвестный режим. Доступно: {value0}',
        'handlers_handle_command_26': 'Режим переключён на {value0}.',
        'handlers_handle_command_27': 'Текущий workspace: `{value0}`\nИспользование: /workspace <путь>, /workspace default',
        'handlers_handle_command_28': 'Workspace сброшен на {value0}.',
        'handlers_handle_command_29': 'Директория не существует: `{value0}`',
        'handlers_handle_command_30': 'Workspace переключён на `{value0}`.',
        'handlers_handle_command_31': 'да, выполняется запрос (можно /stop)',
        'handlers_handle_command_32': 'нет',
        'handlers_handle_command_33': 'не начат',
        'handlers_handle_command_34': 'ℹ️ **Статус**',
        'handlers_handle_command_35': 'Сессия: `{value0}`',
        'handlers_handle_command_36': 'Модель: `{value0}` · Мощность: `{value1}`',
        'handlers_handle_command_37': 'Режим: `{value0}`',
        'handlers_handle_command_38': 'Занят: {value0}',
        'handlers_handle_command_39': 'Аккаунт Claude: {value0}',
        'handlers_handle_command_40': 'Использование: /login или /login delegate',
        'handlers_handle_command_41': 'Начинаю переподключение аккаунта Claude...',
        'handlers_handle_command_42': 'Перезапуск доступен только владельцу.',
        'handlers_handle_command_43': 'SERVICE_NAME не задан в systemd-юните — автоперезапуск недоступен.',
        'handlers_handle_command_44': '🔁 Перезапуск запланирован — выполнится, как только текущие запросы завершатся.',
        'handlers_handle_command_45': 'Обновление доступно только владельцу.',
        'handlers_handle_command_46': 'Настройка локального Bot API уже начата; закончи текущий диалог.',
        'handlers_handle_command_47': '⬇️ Обновляю из git...',
        'handlers_handle_command_48': '❌ Не смог запустить update.sh: {value0}',
        'handlers_handle_command_49': '❌ Обновление не удалось:\n```\n{value0}\n```',
        'handlers_handle_command_50': 'обновлено',
        'handlers_handle_command_51': 'Включить приём файлов до 2 ГБ через локальный Bot API сервер? Да/Нет',
        'handlers_handle_command_52': ' Перезапуск — как только текущие запросы завершатся.',
        'handlers_handle_command_53': ' Перезапуск — между ходами.',
        'handlers_spawn_turn_1': 'Уже выполняю предыдущий запрос. Дождись ответа или используй /stop.',
        'handlers_start_delegate_turn_1': 'Уже выполняю предыдущую делегированную задачу.',
        'handlers_start_delegate_turn_2': 'Делегированный аккаунт Claude не подключён. Используй /login delegate.',
        'handlers_start_delegate_turn_3': 'Нельзя использовать --env вместе с --resume.',
        'handlers_start_delegate_turn_4': 'Нельзя продолжить эту делегацию: resume_session_id не совпадает с последней сессией делегатора.',
        'handlers_start_delegate_turn_5': 'Делегированная задача не запущена.',
        'handlers_send_whitelist_prompt_1': 'Вы не внесены в белый список.\nВаш Telegram ID: `{value0}`\n\nДобавьте его в конфиг через запятую и нажмите на кнопку снизу:',
        'handlers_send_whitelist_prompt_2': 'Готово ✅',
        'handlers_reader_1': '1. Нажми на кнопку ниже\n2. Войди в свой аккаунт Claude\n3. Пришли мне сюда код, который дадут после входа\n\nПримечание: для входа нужна подписка Pro или выше.',
        'handlers_reader_2': '🔗 Войти в Claude',
        'handlers_reader_3': '❌ Не удалось запустить вход Claude. Попробуй /login ещё раз.',
        'handlers_feed_login_code_1': 'Не смог передать код процессу логина. Попробуй /login заново.',
        'handlers_check_1': '✅ Делегированный аккаунт Claude подключён.',
        'handlers_check_2': '✅ Аккаунт подключён. Можно пользоваться ботом.',
        'handlers_check_3': '✅ Аккаунт подключён.\n\nКак к тебе обращаться?',
        'handlers_check_4': 'Не удалось подтвердить вход. Проверь код и попробуй /login ещё раз.',
        'handlers_handle_onboarding_1': 'Перезапускаю вход делегированного Claude — сейчас пришлю новую ссылку.',
        'handlers_handle_onboarding_2': 'Жду код авторизации (пришли его текстом, без команд).',
        'handlers_handle_onboarding_3': 'Перезапускаю вход Claude — сейчас пришлю новую ссылку.',
        'handlers_handle_onboarding_4': '✅ Готово. Можно пользоваться ботом.',
        'handlers_handle_onboarding_5': 'Ты в списке — начинаю подключение твоего аккаунта Claude...',
        'handlers_handle_callback_query_1': 'Ещё не добавлен в список.',
        'handlers_handle_callback_query_2': 'Принято!',
        'handlers_handle_callback_query_3': 'Аккаунт уже подключён.',
        'chat_process_finish_delivery_1': '⚠️ Ответ не удалось доставить в Telegram:\n\n',
        'chat_process_deliver_pending_final_1': '⚠️ Telegram пока не принял ответ, доставка повторяется:\n\n',
        'chat_process_format_turn_footer_1': 'Токены: {value0}',
        'chat_process_format_turn_footer_2': 'Твой session id (до делегации): `{value0}`. Продолжить делегированную: `/resume {value1}`',
        'chat_process_format_turn_footer_3': 'Продолжить делегированную сессию: `/resume {value0}`',
        'chat_process_flush_draft_1': 'Думаю',
        'chat_process_compact_draft_watchdog_1': '🗜 Сжимаю контекст сессии... ({value0}с, это может занять несколько минут)',
        'chat_process_deliver_turn_result_1': '…и ещё {value0} шагов выше…',
        'chat_process_deliver_turn_result_2': '<details><summary>🔧 Процесс ({value0})</summary>\n{value1}\n</details>',
        'chat_process_deliver_turn_result_3': '⏹ Ход прерван — процесс завершился, не дождавшись ответа.',
        'chat_process_deliver_turn_result_4': '(нет ответа — смотри процесс выше)',
        'chat_process_deliver_turn_result_5': '(пусто)',
        'chat_process_deliver_turn_result_6': '🚫 **Заблокировано** (нужно разрешение):',
        'chat_process_deliver_turn_result_7': '/approve — повторить один раз с bypass',
        'chat_process_deliver_turn_result_8': '/approve session — включить bypass насовсем для этой сессии',
        'chat_process_deliver_turn_result_9': '/deny — оставить как есть',
        'chat_process_chat_reader_loop_1': '🗜 Сжимаю контекст сессии...',
        'chat_process_chat_reader_loop_2': 'неизвестная ошибка',
        'chat_process_chat_reader_loop_3': '🗜 Не удалось сжать контекст: {value0}',
        'chat_process_chat_reader_loop_4': '🗜 Контекст сессии сжат.',
        'chat_process_chat_reader_loop_5': '{value0} (пусто)',
        'chat_process_chat_reader_loop_6': 'Ошибка',
        'chat_process_chat_reader_loop_7': 'Результат',
        'telegram_api_send_attachment_1': 'Файл `{value0}` слишком большой для отправки ({value1} байт).',
        'telegram_api_send_attachment_2': 'Не удалось отправить `{value0}`: {value1}',
        'telegram_api_download_error_from_exception_1': 'Файл не скачан: Telegram слишком долго готовил файл. Попробуй ещё раз или дай ссылку.',
        'telegram_api_download_error_from_exception_2': 'Файл не скачан: нет доступа к файлу локального Bot API.',
        'telegram_api_download_error_from_exception_3': 'Файл не скачан: ошибка связи с Telegram. Попробуй ещё раз или дай ссылку.',
        'telegram_api_download_error_from_exception_4': 'Файл не скачан: Telegram не дал получить файл. Попробуй ещё раз или дай ссылку.',
        'telegram_api_get_file_error_1': 'Файл не скачан: размер превышает облачный лимит Telegram 20 МБ. Включи локальный Bot API или дай ссылку.',
        'telegram_api_get_file_error_2': 'Файл не скачан: Telegram отказал в выдаче файла. Отправь его снова или дай ссылку.',
        'telegram_api_download_telegram_file_1': 'Файл не скачан: Telegram не вернул путь к файлу. Попробуй ещё раз или дай ссылку.',
        'telegram_api_download_telegram_file_2': 'Файл не скачан: локальный Bot API больше не видит этот файл. Отправь его снова или дай ссылку.',
        'telegram_api_download_telegram_file_3': 'Файл не скачан: путь локального Bot API не является доступным файлом.',
        'telegram_api_download_telegram_file_4': 'Файл не скачан: размер превышает разрешённый лимит.',
        'runtime_module_1': '🔄 Бот перезапускается — повтори сообщение через минуту.',
        'state_store_add_usage_1': '⚠️ Стоимость этой сессии по API-эквиваленту выросла ещё на ${value0:.0f} (всего ~${value1:.2f}). Есть смысл сделать /compact или начать заново через /new.',
        'state_store_fetch_account_limits_1': '(не удалось получить лимиты: {value0})',
        'state_store_fetch_account_limits_2': '(нет данных)',
        'usage_session_header': '📊 **Сессия**',
        'usage_messages': 'Сообщений: {count}',
        'usage_context': 'Контекст: ~{count} токенов',
        'usage_context_empty': 'Контекст: данных пока нет',
        'usage_tokens_header': '🔢 **Токены (эта сессия)**',
        'usage_calls': 'Запросов: {count}',
        'usage_tokens_line': 'вход {input} · выход {output} · чтение кеша {cache_read} · запись кеша {cache_write}',
        'usage_by_model': '**По моделям**',
        'usage_model_line': '{name}  {input}/{output} вход/выход (~${cost:.4f})',
        'usage_limits_header': '📈 **Лимиты аккаунта** (подписка, не кредиты)',
        'status_workspace': 'Рабочая папка: {workspace}',
        'account_limit_session': 'Текущая сессия',
        'account_limit_week': 'Текущая неделя (все модели)',
        'account_limit_line': '{label}: использовано {percent}% · сброс {reset}',
        'language_usage': 'Использование: /language en|ru|uk|kk|de.',
        'language_command_description': 'Выбрать язык интерфейса и персоны',
        'language_progress': 'Подождите, переключаем язык на русский…',
        'language_changed': 'Язык переключён на русский.',
        'language_persona_failed': 'Язык интерфейса переключён на русский, но перевести персону не удалось: {error}',
    },
    "en": {
        'language_usage': 'Usage: /language en|ru|uk|kk|de.',
        'language_progress': 'Please wait, switching to English…',
        'language_changed': 'Language switched to English.',
        'language_persona_failed': 'The interface is now in English, but the persona could not be translated: {error}',
    },
    "uk": {
        'language_usage': 'Використання: /language en|ru|uk|kk|de.',
        'language_progress': 'Зачекайте, перемикаємо мову на українську…',
        'language_changed': 'Мову змінено на українську.',
        'language_persona_failed': 'Мову інтерфейсу змінено на українську, але персону не вдалося перекласти: {error}',
    },
    "kk": {
        'language_usage': 'Қолданылуы: /language en|ru|uk|kk|de.',
        'language_progress': 'Күте тұрыңыз, тілді қазақ тіліне ауыстырып жатырмыз…',
        'language_changed': 'Тіл қазақ тіліне ауыстырылды.',
        'language_persona_failed': 'Интерфейс тілі қазақ тіліне ауыстырылды, бірақ персонаны аудару мүмкін болмады: {error}',
    },
    "de": {
        'language_usage': 'Verwendung: /language en|ru|uk|kk|de.',
        'language_progress': 'Bitte warten, wir wechseln auf Deutsch …',
        'language_changed': 'Sprache auf Deutsch umgestellt.',
        'language_persona_failed': 'Die Oberfläche wurde auf Deutsch umgestellt, aber die Persona konnte nicht übersetzt werden: {error}',
    },
}


COMMAND_DESCRIPTIONS = {
    "ru": {
        "language": "Выбрать язык интерфейса и персоны", "new": "Начать новую сессию",
        "sessions": "Список последних сессий", "resume": "Продолжить сессию по ID",
        "status": "Показать состояние сессии", "stop": "Остановить текущий запрос",
        "compact": "Сжать контекст сессии", "usage": "Токены, стоимость и лимиты",
        "model": "Выбрать модель Claude", "effort": "Выбрать мощность модели",
        "mode": "Выбрать режим подтверждений", "workspace": "Выбрать рабочую папку",
        "approve": "Разрешить заблокированное действие", "deny": "Отклонить действие",
        "login": "Переподключить аккаунт Claude", "restart": "Перезапустить бота (владелец)",
        "update": "Обновить из Git и перезапустить (владелец)",
    },
    "en": {
        "language": "Choose interface and persona language", "new": "Start a new session",
        "sessions": "List recent sessions", "resume": "Resume a session by ID",
        "status": "Show session status", "stop": "Stop the current request",
        "compact": "Compact session context", "usage": "Tokens, cost and account limits",
        "model": "Choose a Claude model", "effort": "Choose model effort",
        "mode": "Choose approval mode", "workspace": "Choose working directory",
        "approve": "Approve a blocked action", "deny": "Deny a blocked action",
        "login": "Reconnect your Claude account", "restart": "Restart the bot (owner only)",
        "update": "Update from Git and restart (owner only)",
    },
    "uk": {
        "language": "Вибрати мову інтерфейсу й персони", "new": "Почати новий сеанс",
        "sessions": "Список останніх сеансів", "resume": "Продовжити сеанс за ID",
        "status": "Показати стан сеансу", "stop": "Зупинити поточний запит",
        "compact": "Стиснути контекст сеансу", "usage": "Токени, вартість і ліміти",
        "model": "Вибрати модель Claude", "effort": "Вибрати рівень зусиль моделі",
        "mode": "Вибрати режим підтверджень", "workspace": "Вибрати робочу папку",
        "approve": "Дозволити заблоковану дію", "deny": "Відхилити дію",
        "login": "Повторно підключити акаунт Claude", "restart": "Перезапустити бота (власник)",
        "update": "Оновити з Git і перезапустити (власник)",
    },
    "kk": {
        "language": "Интерфейс пен персона тілін таңдау", "new": "Жаңа сеансты бастау",
        "sessions": "Соңғы сеанстар тізімі", "resume": "Сеансты ID арқылы жалғастыру",
        "status": "Сеанс күйін көрсету", "stop": "Ағымдағы сұрауды тоқтату",
        "compact": "Сеанс контекстін қысқарту", "usage": "Токендер, құн және лимиттер",
        "model": "Claude моделін таңдау", "effort": "Модель күш салу деңгейін таңдау",
        "mode": "Рұқсат беру режимін таңдау", "workspace": "Жұмыс бумасын таңдау",
        "approve": "Бұғатталған әрекетке рұқсат беру", "deny": "Әрекеттен бас тарту",
        "login": "Claude аккаунтын қайта қосу", "restart": "Ботты қайта іске қосу (иесі)",
        "update": "Git-тен жаңартып, қайта іске қосу (иесі)",
    },
    "de": {
        "language": "Sprache für Oberfläche und Persona wählen", "new": "Neue Sitzung starten",
        "sessions": "Letzte Sitzungen anzeigen", "resume": "Sitzung anhand der ID fortsetzen",
        "status": "Sitzungsstatus anzeigen", "stop": "Aktuelle Anfrage stoppen",
        "compact": "Sitzungskontext komprimieren", "usage": "Tokens, Kosten und Kontolimits",
        "model": "Claude-Modell auswählen", "effort": "Leistungsstufe des Modells wählen",
        "mode": "Bestätigungsmodus wählen", "workspace": "Arbeitsverzeichnis wählen",
        "approve": "Blockierte Aktion genehmigen", "deny": "Blockierte Aktion ablehnen",
        "login": "Claude-Konto erneut verbinden", "restart": "Bot neu starten (nur Inhaber)",
        "update": "Aus Git aktualisieren und neu starten (nur Inhaber)",
    },
}


_COMMAND_OUTPUTS = {
    "handlers_handle_command_1": ("The persona is available only to the owner in a private chat.", "Персона доступна лише власнику в особистому чаті.", "Персона тек жеке чатта иесіне ғана қолжетімді.", "Die Persona ist nur für den Inhaber im privaten Chat verfügbar."),
    "handlers_handle_command_2": ("✅ Persona reset to the default template.", "✅ Персону скинуто до стандартного шаблону.", "✅ Персона әдепкі үлгіге қайтарылды.", "✅ Persona auf die Standardvorlage zurückgesetzt."),
    "handlers_handle_command_3": ("Usage: /persona or /persona reset", "Використання: /persona або /persona reset", "Қолданылуы: /persona немесе /persona reset", "Verwendung: /persona oder /persona reset"),
    "handlers_handle_command_4": ("Starting a new session.", "Починаю новий сеанс.", "Жаңа сеансты бастаймын.", "Neue Sitzung wird gestartet."),
    "handlers_handle_command_5": ("No sessions found.", "Сеансів не знайдено.", "Сеанстар табылмады.", "Keine Sitzungen gefunden."),
    "handlers_handle_command_6": ("Recent sessions:", "Останні сеанси:", "Соңғы сеанстар:", "Letzte Sitzungen:"),
    "handlers_handle_command_7": (" ← current", " ← поточний", " ← ағымдағы", " ← aktuell"),
    "handlers_handle_command_8": ("Usage: /resume <session ID or prefix>", "Використання: /resume <ID сеансу або префікс>", "Қолданылуы: /resume <сеанс ID-і немесе префикс>", "Verwendung: /resume <Sitzungs-ID oder Präfix>"),
    "handlers_handle_command_9": ("Session {value0} not found.", "Сеанс {value0} не знайдено.", "{value0} сеансы табылмады.", "Sitzung {value0} nicht gefunden."),
    "handlers_handle_command_10": ("Prefix {value0} matches several sessions; provide more of the ID:", "Префікс {value0} відповідає кільком сеансам; уточни ID:", "{value0} префиксі бірнеше сеансқа сәйкес келеді; ID-ді нақтыла:", "Präfix {value0} passt zu mehreren Sitzungen; bitte die ID präzisieren:"),
    "handlers_handle_command_11": ("…and {value0} more", "…і ще {value0}", "…және тағы {value0}", "…und {value0} weitere"),
    "handlers_handle_command_12": ("Resuming {value0}session {value1}.", "Продовжую {value0}сеанс {value1}.", "{value0}{value1} сеансын жалғастырамын.", "Setze {value0}Sitzung {value1} fort."),
    "handlers_handle_command_13": ("delegated ", "делегований ", "делегирленген ", "delegierte "),
    "handlers_handle_command_14": ("\x60{value0}\x60  •  Model: {value1}  •  Effort: {value2}", "\x60{value0}\x60  •  Модель: {value1}  •  Рівень зусиль: {value2}", "\x60{value0}\x60  •  Модель: {value1}  •  Күш салу: {value2}", "\x60{value0}\x60  •  Modell: {value1}  •  Leistungsstufe: {value2}"),
    "handlers_handle_command_15": ("none active", "немає активного", "белсендісі жоқ", "keine aktive"),
    "handlers_handle_command_16": ("(~${value0:.4f} at equivalent API rates)", "(~${value0:.4f} за еквівалентним тарифом API)", "(~${value0:.4f} балама API тарифімен)", "(~${value0:.4f} zum entsprechenden API-Tarif)"),
    "handlers_handle_command_17": ("Model “{value0}” is unavailable.\n\n{value1}", "Модель «{value0}» недоступна.\n\n{value1}", "«{value0}» моделі қолжетімсіз.\n\n{value1}", "Modell „{value0}“ ist nicht verfügbar.\n\n{value1}"),
    "handlers_handle_command_18": ("CLI default", "Типова модель CLI", "CLI әдепкі моделі", "CLI-Standard"),
    "handlers_handle_command_19": ("🧠 Model: {value0}", "🧠 Модель: {value0}", "🧠 Модель: {value0}", "🧠 Modell: {value0}"),
    "handlers_handle_command_20": ("Effort: {value0}", "Рівень зусиль: {value0}", "Күш салу: {value0}", "Leistungsstufe: {value0}"),
    "handlers_handle_command_21": ("The selected effort is not supported by the new model and was reset.", "Обраний рівень зусиль не підтримується новою моделлю; налаштування скинуто.", "Таңдалған күш салу деңгейін жаңа модель қолдамайды; ол қалпына келтірілді.", "Die gewählte Leistungsstufe wird vom neuen Modell nicht unterstützt und wurde zurückgesetzt."),
    "handlers_handle_command_22": ("Effort “{value0}” is unavailable for {value1}.\n\n{value2}", "Рівень зусиль «{value0}» недоступний для {value1}.\n\n{value2}", "«{value0}» күш салу деңгейі {value1} үшін қолжетімсіз.\n\n{value2}", "Leistungsstufe „{value0}“ ist für {value1} nicht verfügbar.\n\n{value2}"),
    "handlers_handle_command_23": ("⚡ {value0} effort: {value1}", "⚡ Рівень зусиль {value0}: {value1}", "⚡ {value0} күш салуы: {value1}", "⚡ Leistungsstufe für {value0}: {value1}"),
    "handlers_handle_command_24": ("Current mode: \x60{value0}\x60\nAvailable: {value1}\n\nbypass — no confirmations (default)\ndefault — dangerous actions require /approve\nacceptEdits — file edits are automatic; other actions require /approve\nplan — read-only; no changes", "Поточний режим: \x60{value0}\x60\nДоступні: {value1}\n\nbypass — без підтверджень (типово)\ndefault — небезпечні дії потребують /approve\nacceptEdits — зміни файлів автоматичні; інші дії потребують /approve\nplan — лише читання, без змін", "Ағымдағы режим: \x60{value0}\x60\nҚолжетімді: {value1}\n\nbypass — растаусыз (әдепкі)\ndefault — қауіпті әрекеттер үшін /approve қажет\nacceptEdits — файл өзгерістері автоматты; басқа әрекеттер үшін /approve қажет\nplan — тек оқу, өзгеріссіз", "Aktueller Modus: \x60{value0}\x60\nVerfügbar: {value1}\n\nbypass — keine Bestätigungen (Standard)\ndefault — gefährliche Aktionen erfordern /approve\nacceptEdits — Dateiänderungen automatisch; andere Aktionen erfordern /approve\nplan — nur lesen, keine Änderungen"),
    "handlers_handle_command_25": ("Unknown mode. Available: {value0}", "Невідомий режим. Доступні: {value0}", "Белгісіз режим. Қолжетімді: {value0}", "Unbekannter Modus. Verfügbar: {value0}"),
    "handlers_handle_command_26": ("Mode changed to {value0}.", "Режим змінено на {value0}.", "Режим {value0} болып өзгертілді.", "Modus auf {value0} geändert."),
    "handlers_handle_command_27": ("Current working directory: \x60{value0}\x60\nUsage: /workspace <path> or /workspace default", "Поточна робоча папка: \x60{value0}\x60\nВикористання: /workspace <шлях> або /workspace default", "Ағымдағы жұмыс бумасы: \x60{value0}\x60\nҚолданылуы: /workspace <жол> немесе /workspace default", "Aktuelles Arbeitsverzeichnis: \x60{value0}\x60\nVerwendung: /workspace <Pfad> oder /workspace default"),
    "handlers_handle_command_28": ("Working directory reset to {value0}.", "Робочу папку скинуто до {value0}.", "Жұмыс бумасы {value0} болып қалпына келтірілді.", "Arbeitsverzeichnis auf {value0} zurückgesetzt."),
    "handlers_handle_command_29": ("Directory does not exist: \x60{value0}\x60", "Каталогу не існує: \x60{value0}\x60", "Бума жоқ: \x60{value0}\x60", "Verzeichnis existiert nicht: \x60{value0}\x60"),
    "handlers_handle_command_30": ("Working directory changed to \x60{value0}\x60.", "Робочу папку змінено на \x60{value0}\x60.", "Жұмыс бумасы \x60{value0}\x60 болып өзгертілді.", "Arbeitsverzeichnis auf \x60{value0}\x60 geändert."),
    "handlers_handle_command_31": ("yes, a request is running (use /stop)", "так, запит виконується (можна /stop)", "иә, сұрау орындалуда (/stop қолдануға болады)", "ja, eine Anfrage läuft (/stop möglich)"),
    "handlers_handle_command_32": ("no", "ні", "жоқ", "nein"),
    "handlers_handle_command_33": ("not started", "не розпочато", "басталмаған", "nicht gestartet"),
    "handlers_handle_command_34": ("ℹ️ **Status**", "ℹ️ **Стан**", "ℹ️ **Күйі**", "ℹ️ **Status**"),
    "handlers_handle_command_35": ("Session: \x60{value0}\x60", "Сеанс: \x60{value0}\x60", "Сеанс: \x60{value0}\x60", "Sitzung: \x60{value0}\x60"),
    "handlers_handle_command_36": ("Model: \x60{value0}\x60 · Effort: \x60{value1}\x60", "Модель: \x60{value0}\x60 · Рівень зусиль: \x60{value1}\x60", "Модель: \x60{value0}\x60 · Күш салу: \x60{value1}\x60", "Modell: \x60{value0}\x60 · Leistungsstufe: \x60{value1}\x60"),
    "handlers_handle_command_37": ("Mode: \x60{value0}\x60", "Режим: \x60{value0}\x60", "Режим: \x60{value0}\x60", "Modus: \x60{value0}\x60"),
    "handlers_handle_command_38": ("Busy: {value0}", "Зайнятий: {value0}", "Орындалып жатыр: {value0}", "Beschäftigt: {value0}"),
    "handlers_handle_command_39": ("Claude account: {value0}", "Акаунт Claude: {value0}", "Claude аккаунты: {value0}", "Claude-Konto: {value0}"),
    "handlers_handle_command_40": ("Usage: /login or /login delegate", "Використання: /login або /login delegate", "Қолданылуы: /login немесе /login delegate", "Verwendung: /login oder /login delegate"),
    "handlers_handle_command_41": ("Starting Claude account reconnection…", "Починаю повторне підключення акаунта Claude…", "Claude аккаунтын қайта қосуды бастаймын…", "Claude-Konto wird erneut verbunden …"),
    "handlers_handle_command_42": ("Only the owner can restart the bot.", "Лише власник може перезапустити бота.", "Ботты тек иесі қайта іске қоса алады.", "Nur der Inhaber kann den Bot neu starten."),
    "handlers_handle_command_43": ("SERVICE_NAME is not set in the systemd unit; automatic restart is unavailable.", "SERVICE_NAME не задано в юніті systemd; автоматичний перезапуск недоступний.", "SERVICE_NAME systemd юнитінде орнатылмаған; автоматты қайта іске қосу қолжетімсіз.", "SERVICE_NAME ist in der systemd-Unit nicht gesetzt; automatischer Neustart ist nicht verfügbar."),
    "handlers_handle_command_44": ("🔁 Restart scheduled after current requests finish.", "🔁 Перезапуск заплановано після завершення поточних запитів.", "🔁 Ағымдағы сұраулар аяқталған соң қайта іске қосу жоспарланды.", "🔁 Neustart nach Abschluss der laufenden Anfragen geplant."),
    "handlers_handle_command_45": ("Only the owner can update the bot.", "Лише власник може оновити бота.", "Ботты тек иесі жаңарта алады.", "Nur der Inhaber kann den Bot aktualisieren."),
    "handlers_handle_command_46": ("Local Bot API setup is already in progress; finish the current dialog.", "Налаштування локального Bot API вже триває; заверши поточний діалог.", "Жергілікті Bot API баптауы жүріп жатыр; ағымдағы диалогты аяқта.", "Die Einrichtung der lokalen Bot API läuft bereits; schließe den aktuellen Dialog ab."),
    "handlers_handle_command_47": ("⬇️ Updating from Git…", "⬇️ Оновлюю з Git…", "⬇️ Git-тен жаңартып жатырмын…", "⬇️ Aktualisiere aus Git …"),
    "handlers_handle_command_48": ("❌ Could not run update.sh: {value0}", "❌ Не вдалося запустити update.sh: {value0}", "❌ update.sh іске қосылмады: {value0}", "❌ update.sh konnte nicht gestartet werden: {value0}"),
    "handlers_handle_command_49": ("❌ Update failed:\n\x60\x60\x60\n{value0}\n\x60\x60\x60", "❌ Оновлення не вдалося:\n\x60\x60\x60\n{value0}\n\x60\x60\x60", "❌ Жаңарту сәтсіз аяқталды:\n\x60\x60\x60\n{value0}\n\x60\x60\x60", "❌ Aktualisierung fehlgeschlagen:\n\x60\x60\x60\n{value0}\n\x60\x60\x60"),
    "handlers_handle_command_50": ("updated", "оновлено", "жаңартылды", "aktualisiert"),
    "handlers_handle_command_51": ("Enable file uploads up to 2 GB through a local Bot API server? Yes/No", "Увімкнути приймання файлів до 2 ГБ через локальний сервер Bot API? Так/Ні", "Жергілікті Bot API сервері арқылы 2 ГБ-қа дейінгі файлдарды қабылдау қосылсын ба? Иә/Жоқ", "Dateien bis 2 GB über einen lokalen Bot-API-Server zulassen? Ja/Nein"),
    "handlers_handle_command_52": (" Restart after current requests finish.", " Перезапуск після завершення поточних запитів.", " Ағымдағы сұраулар аяқталған соң қайта іске қосылады.", " Neustart nach Abschluss der laufenden Anfragen."),
    "handlers_handle_command_53": (" Restart between turns.", " Перезапуск між ходами.", " Жауаптар арасында қайта іске қосылады.", " Neustart zwischen zwei Durchläufen."),
    "handlers_model_from_spec_1": ("Unknown model family “{value0}”. Available: {value1}, default", "Невідоме сімейство моделей «{value0}». Доступні: {value1}, default", "«{value0}» модель тобы белгісіз. Қолжетімді: {value1}, default", "Unbekannte Modellfamilie „{value0}“. Verfügbar: {value1}, default"),
    "handlers_model_from_spec_2": ("No {value0} version {value1} exists.", "Версії {value1} для {value0} немає.", "{value0} моделінің {value1} нұсқасы жоқ.", "Version {value1} von {value0} ist nicht verfügbar."),
    "handlers_resolve_effort_spec_1": ("CLI default model", "Типова модель CLI", "CLI әдепкі моделі", "CLI-Standardmodell"),
    "handlers_resolve_effort_spec_2": ("Effort “{value0}” is unavailable for {value1}.", "Рівень зусиль «{value0}» недоступний для {value1}.", "«{value0}» күш салу деңгейі {value1} үшін қолжетімсіз.", "Leistungsstufe „{value0}“ ist für {value1} nicht verfügbar."),
    "handlers_effort_label_1": ("not supported", "не підтримується", "қолданылмайды", "nicht unterstützt"),
    "handlers_effort_label_2": ("default", "типово", "әдепкі", "Standard"),
    "handlers_render_model_picker_1": ("🧠 Claude models:", "🧠 Моделі Claude:", "🧠 Claude модельдері:", "🧠 Claude-Modelle:"),
    "handlers_render_model_picker_2": ("{value0} CLI default — \x60/model default\x60", "{value0} Типова модель CLI — \x60/model default\x60", "{value0} CLI әдепкі моделі — \x60/model default\x60", "{value0} CLI-Standard — \x60/model default\x60"),
    "handlers_render_model_picker_3": ("⚡ Effort: {value0}. Choose: /effort", "⚡ Рівень зусиль: {value0}. Вибрати: /effort", "⚡ Күш салу: {value0}. Таңдау: /effort", "⚡ Leistungsstufe: {value0}. Auswahl: /effort"),
    "handlers_render_effort_picker_1": ("⚡ {value0} does not support effort settings.", "⚡ {value0} не підтримує налаштування рівня зусиль.", "⚡ {value0} күш салу параметрін қолдамайды.", "⚡ {value0} unterstützt keine Einstellung der Leistungsstufe."),
    "handlers_render_effort_picker_2": ("CLI default", "Типова модель CLI", "CLI әдепкі моделі", "CLI-Standard"),
    "handlers_render_effort_picker_3": ("⚡ Effort for {value0}:", "⚡ Рівень зусиль моделі {value0}:", "⚡ {value0} күш салу деңгейі:", "⚡ Leistungsstufe für {value0}:"),
    "handlers_render_effort_picker_4": ("{value0} CLI default — \x60/effort default\x60", "{value0} Типово для CLI — \x60/effort default\x60", "{value0} CLI әдепкісі — \x60/effort default\x60", "{value0} CLI-Standard — \x60/effort default\x60"),
    "usage_session_header": ("📊 **Session**", "📊 **Сеанс**", "📊 **Сеанс**", "📊 **Sitzung**"),
    "usage_messages": ("Messages: {count}", "Повідомлень: {count}", "Хабарлар: {count}", "Nachrichten: {count}"),
    "usage_context": ("Context: ~{count} tokens", "Контекст: ~{count} токенів", "Контекст: ~{count} токен", "Kontext: ~{count} Tokens"),
    "usage_context_empty": ("Context: no data yet", "Контекст: даних поки немає", "Контекст: әзірге дерек жоқ", "Kontext: noch keine Daten"),
    "usage_tokens_header": ("🔢 **Tokens (this session)**", "🔢 **Токени (цей сеанс)**", "🔢 **Токендер (осы сеанс)**", "🔢 **Tokens (diese Sitzung)**"),
    "usage_calls": ("Calls: {count}", "Запитів: {count}", "Сұраулар: {count}", "Aufrufe: {count}"),
    "usage_tokens_line": ("in {input} · out {output} · cache read {cache_read} · cache write {cache_write}", "вх. {input} · вих. {output} · читання кешу {cache_read} · запис кешу {cache_write}", "кіріс {input} · шығыс {output} · кэш оқу {cache_read} · кэш жазу {cache_write}", "Eingabe {input} · Ausgabe {output} · Cache-Lesen {cache_read} · Cache-Schreiben {cache_write}"),
    "usage_by_model": ("**By model**", "**За моделями**", "**Модельдер бойынша**", "**Nach Modell**"),
    "usage_model_line": ("{name}  {input}/{output} in/out (~${cost:.4f})", "{name}  {input}/{output} вх./вих. (~${cost:.4f})", "{name}  {input}/{output} кіріс/шығыс (~${cost:.4f})", "{name}  {input}/{output} Ein-/Ausgabe (~${cost:.4f})"),
    "usage_limits_header": ("📈 **Account limits** (subscription, not credits)", "📈 **Ліміти акаунта** (підписка, не кредити)", "📈 **Аккаунт лимиттері** (жазылым, кредит емес)", "📈 **Kontolimits** (Abonnement, kein Guthaben)"),
    "status_workspace": ("Working directory: {workspace}", "Робоча папка: {workspace}", "Жұмыс бумасы: {workspace}", "Arbeitsverzeichnis: {workspace}"),
    "account_limit_session": ("Current session", "Поточний сеанс", "Ағымдағы сеанс", "Aktuelle Sitzung"),
    "account_limit_week": ("Current week (all models)", "Поточний тиждень (усі моделі)", "Ағымдағы апта (барлық модельдер)", "Aktuelle Woche (alle Modelle)"),
    "account_limit_line": ("{label}: {percent}% used · resets {reset}", "{label}: використано {percent}% · скидання {reset}", "{label}: {percent}% пайдаланылды · қалпына келуі {reset}", "{label}: {percent}% verbraucht · Zurücksetzung {reset}"),
    "bridge_process_message_1": ("⏹ Stopping the current request…", "⏹ Зупиняю поточний запит…", "⏹ Ағымдағы сұрауды тоқтатып жатырмын…", "⏹ Aktuelle Anfrage wird gestoppt …"),
    "bridge_process_message_2": ("Nothing is running right now.", "Зараз нічого не виконується.", "Қазір ештеңе орындалып жатқан жоқ.", "Im Moment läuft nichts."),
    "bridge_process_message_3": ("No blocked action to approve.", "Немає заблокованої дії для підтвердження.", "Рұқсат берілетін бұғатталған әрекет жоқ.", "Keine blockierte Aktion zum Genehmigen vorhanden."),
    "bridge_process_message_4": ("The blocked action belongs to an earlier session; it will not be retried here.", "Заблокована дія належить до попереднього сеансу; тут її не повторюватиму.", "Бұғатталған әрекет алдыңғы сеансқа тиесілі; бұл жерде қайталанбайды.", "Die blockierte Aktion gehört zu einer früheren Sitzung und wird hier nicht wiederholt."),
    "bridge_process_message_5": ("Bypass enabled for this session. Retrying…", "Bypass увімкнено для цього сеансу. Повторюю…", "Bypass осы сеанс үшін қосылды. Қайталаймын…", "Bypass für diese Sitzung aktiviert. Neuer Versuch …"),
    "bridge_process_message_6": ("Approved once. Retrying…", "Дозволено один раз. Повторюю…", "Бір рет рұқсат берілді. Қайталаймын…", "Einmal genehmigt. Neuer Versuch …"),
    "bridge_process_message_7": ("Denied.", "Відхилено.", "Қабылданбады.", "Abgelehnt."),
    "bridge_process_message_8": ("Nothing to deny.", "Немає чого відхиляти.", "Бас тартатын әрекет жоқ.", "Nichts zum Ablehnen vorhanden."),
    "handlers_send_persona_1": ("Current persona", "Поточна персона", "Ағымдағы персона", "Aktuelle Persona"),
    "handlers_handle_persona_reply_1": ("The persona file must be UTF-8 Markdown text.", "Файл персони має бути текстовим Markdown-файлом у UTF-8.", "Персона файлы UTF-8 кодтауындағы Markdown мәтіні болуы керек.", "Die Persona-Datei muss eine UTF-8-Markdown-Textdatei sein."),
    "handlers_handle_persona_reply_2": ("Could not read the persona file: {value0}", "Не вдалося прочитати файл персони: {value0}", "Персона файлын оқу мүмкін болмады: {value0}", "Persona-Datei konnte nicht gelesen werden: {value0}"),
    "handlers_handle_persona_reply_3": ("Reply with persona text or a UTF-8 Markdown file.", "Надішли текст персони або UTF-8 Markdown-файл у відповіді на повідомлення.", "Хабарламаға жауап ретінде персона мәтінін немесе UTF-8 Markdown файлын жібер.", "Antworte mit dem Persona-Text oder einer UTF-8-Markdown-Datei."),
    "handlers_handle_persona_reply_4": ("An empty persona was not saved.", "Порожню персону не збережено.", "Бос персона сақталмады.", "Eine leere Persona wurde nicht gespeichert."),
    "handlers_handle_persona_reply_5": ("✅ Persona updated.", "✅ Персону оновлено.", "✅ Персона жаңартылды.", "✅ Persona aktualisiert."),
    "handlers_spawn_turn_1": ("The previous request is still running. Wait for it or use /stop.", "Попередній запит ще виконується. Дочекайся відповіді або використай /stop.", "Алдыңғы сұрау әлі орындалуда. Жауабын күт немесе /stop қолдан.", "Die vorherige Anfrage läuft noch. Warte auf die Antwort oder nutze /stop."),
    "chat_process_chat_reader_loop_1": ("🗜 Compacting session context…", "🗜 Стискаю контекст сеансу…", "🗜 Сеанс контекстін қысқартып жатырмын…", "🗜 Sitzungskontext wird komprimiert …"),
    "chat_process_chat_reader_loop_2": ("unknown error", "невідома помилка", "белгісіз қате", "unbekannter Fehler"),
    "chat_process_chat_reader_loop_3": ("🗜 Could not compact context: {value0}", "🗜 Не вдалося стиснути контекст: {value0}", "🗜 Контекстті қысқарту мүмкін болмады: {value0}", "🗜 Kontext konnte nicht komprimiert werden: {value0}"),
    "chat_process_chat_reader_loop_4": ("🗜 Session context compacted.", "🗜 Контекст сеансу стиснуто.", "🗜 Сеанс контексті қысқартылды.", "🗜 Sitzungskontext komprimiert."),
    "chat_process_compact_draft_watchdog_1": ("🗜 Compacting session context… ({value0}s; this may take several minutes)", "🗜 Стискаю контекст сеансу… ({value0} с; це може тривати кілька хвилин)", "🗜 Сеанс контекстін қысқартып жатырмын… ({value0} с; бірнеше минут кетуі мүмкін)", "🗜 Sitzungskontext wird komprimiert … ({value0} s; das kann einige Minuten dauern)"),
    "handlers_reader_1": ("1. Tap the button below\n2. Sign in to your Claude account\n3. Send me the code you receive\n\nA Pro subscription or higher is required.", "1. Натисни кнопку нижче\n2. Увійди у свій акаунт Claude\n3. Надішли мені отриманий код\n\nПотрібна підписка Pro або вище.", "1. Төмендегі түймені бас\n2. Claude аккаунтыңа кір\n3. Алған кодты маған жібер\n\nPro немесе жоғары жазылым қажет.", "1. Tippe auf die Schaltfläche unten\n2. Melde dich bei deinem Claude-Konto an\n3. Sende mir den erhaltenen Code\n\nEin Pro-Abonnement oder höher ist erforderlich."),
    "handlers_reader_2": ("🔗 Sign in to Claude", "🔗 Увійти в Claude", "🔗 Claude жүйесіне кіру", "🔗 Bei Claude anmelden"),
    "handlers_reader_3": ("❌ Could not start Claude sign-in. Try /login again.", "❌ Не вдалося почати вхід у Claude. Спробуй /login ще раз.", "❌ Claude жүйесіне кіру басталмады. /login пәрменін қайтала.", "❌ Claude-Anmeldung konnte nicht gestartet werden. Versuche /login erneut."),
    "handlers_feed_login_code_1": ("Could not pass the code to the login process. Try /login again.", "Не вдалося передати код процесу входу. Спробуй /login ще раз.", "Кодты кіру процесіне беру мүмкін болмады. /login пәрменін қайтала.", "Code konnte nicht an den Anmeldeprozess übergeben werden. Versuche /login erneut."),
    "handlers_check_1": ("✅ Delegated Claude account connected.", "✅ Делегований акаунт Claude підключено.", "✅ Делегирленген Claude аккаунты қосылды.", "✅ Delegiertes Claude-Konto verbunden."),
    "handlers_check_2": ("✅ Account connected. You can use the bot.", "✅ Акаунт підключено. Можна користуватися ботом.", "✅ Аккаунт қосылды. Ботты пайдалануға болады.", "✅ Konto verbunden. Der Bot ist bereit."),
    "handlers_check_3": ("✅ Account connected.\n\nHow should I address you?", "✅ Акаунт підключено.\n\nЯк до тебе звертатися?", "✅ Аккаунт қосылды.\n\nСаған қалай жүгінейін?", "✅ Konto verbunden.\n\nWie soll ich dich ansprechen?"),
    "handlers_check_4": ("Could not confirm sign-in. Check the code and try /login again.", "Не вдалося підтвердити вхід. Перевір код і спробуй /login ще раз.", "Кіруді растау мүмкін болмады. Кодты тексеріп, /login пәрменін қайтала.", "Anmeldung konnte nicht bestätigt werden. Prüfe den Code und versuche /login erneut."),
    "handlers_handle_onboarding_1": ("Restarting delegated Claude sign-in; I will send a new link shortly.", "Перезапускаю вхід делегованого Claude; зараз надішлю нове посилання.", "Делегирленген Claude кіруін қайта бастаймын; жаңа сілтемені жіберемін.", "Anmeldung für das delegierte Claude-Konto wird neu gestartet; gleich kommt ein neuer Link."),
    "handlers_handle_onboarding_2": ("Waiting for the authorization code (send it as text, without a command).", "Чекаю на код авторизації (надішли його текстом, без команди).", "Авторизация кодын күтіп тұрмын (пәрменсіз мәтін ретінде жібер).", "Ich warte auf den Autorisierungscode (als Text senden, ohne Befehl)."),
    "handlers_handle_onboarding_3": ("Restarting Claude sign-in; I will send a new link shortly.", "Перезапускаю вхід у Claude; зараз надішлю нове посилання.", "Claude кіруін қайта бастаймын; жаңа сілтемені жіберемін.", "Claude-Anmeldung wird neu gestartet; gleich kommt ein neuer Link."),
    "handlers_handle_onboarding_4": ("✅ Done. You can use the bot.", "✅ Готово. Можна користуватися ботом.", "✅ Дайын. Ботты пайдалануға болады.", "✅ Fertig. Der Bot ist bereit."),
    "handlers_handle_onboarding_5": ("You are on the allowlist; connecting your Claude account…", "Ти в списку дозволених; підключаю твій акаунт Claude…", "Сен рұқсат тізіміндесің; Claude аккаунтыңды қосып жатырмын…", "Du stehst auf der Freigabeliste; dein Claude-Konto wird verbunden …"),
    "handlers_handle_callback_query_1": ("Not on the allowlist yet.", "Ще не додано до списку дозволених.", "Әлі рұқсат тізімінде жоқ.", "Noch nicht auf der Freigabeliste."),
    "handlers_handle_callback_query_2": ("Accepted!", "Прийнято!", "Қабылданды!", "Angenommen!"),
    "handlers_handle_callback_query_3": ("Account already connected.", "Акаунт уже підключено.", "Аккаунт әлдеқашан қосылған.", "Konto bereits verbunden."),
    "handlers_telegram_bot_api_unit_1": ("Invalid local Bot API unit name.", "Некоректна назва юніта локального Bot API.", "Жергілікті Bot API юнитінің атауы қате.", "Ungültiger Name der lokalen Bot-API-Unit."),
    "handlers_repair_local_bot_api_service_1": ("⚠️ The local server is configured, but its systemd unit is not installed. Run scripts/install-local-bot-api.sh manually.", "⚠️ Локальний сервер налаштовано, але його юніт systemd не встановлено. Запусти scripts/install-local-bot-api.sh вручну.", "⚠️ Жергілікті сервер бапталған, бірақ systemd юниті орнатылмаған. scripts/install-local-bot-api.sh скриптін қолмен іске қос.", "⚠️ Der lokale Server ist konfiguriert, aber seine systemd-Unit fehlt. Führe scripts/install-local-bot-api.sh manuell aus."),
    "handlers_repair_local_bot_api_service_2": ("⚠️ Could not restart the local server: {value0}", "⚠️ Не вдалося перезапустити локальний сервер: {value0}", "⚠️ Жергілікті серверді қайта іске қосу мүмкін болмады: {value0}", "⚠️ Lokaler Server konnte nicht neu gestartet werden: {value0}"),
    "handlers_repair_local_bot_api_service_3": ("command failed", "команда завершилася з помилкою", "пәрмен сәтсіз аяқталды", "Befehl fehlgeschlagen"),
    "handlers_repair_local_bot_api_service_4": ("🔧 The local server was inactive; its unit was restarted.", "🔧 Локальний сервер був неактивний; його юніт перезапущено.", "🔧 Жергілікті сервер белсенді емес еді; юнит қайта іске қосылды.", "🔧 Der lokale Server war inaktiv; seine Unit wurde neu gestartet."),
    "handlers_write_telegram_api_url_1": ("Installer returned an invalid local server address", "Інсталятор повернув некоректну адресу локального сервера", "Орнатушы жергілікті сервердің қате мекенжайын қайтарды", "Installationsprogramm lieferte eine ungültige lokale Serveradresse"),
    "handlers_write_telegram_api_url_2": ("Bridge environment file not found: {value0}", "Env-файл моста не знайдено: {value0}", "Көпірдің орта файлы табылмады: {value0}", "Umgebungsdatei der Bridge nicht gefunden: {value0}"),
    "handlers_finish_local_bot_api_setup_1": ("⚠️ Could not enable the local server: {value0}", "⚠️ Не вдалося ввімкнути локальний сервер: {value0}", "⚠️ Жергілікті серверді қосу мүмкін болмады: {value0}", "⚠️ Lokaler Server konnte nicht aktiviert werden: {value0}"),
    "handlers_finish_local_bot_api_setup_2": ("✅ Local server enabled. Restarting the bot…", "✅ Локальний сервер увімкнено. Перезапускаю бота…", "✅ Жергілікті сервер қосылды. Бот қайта іске қосылады…", "✅ Lokaler Server aktiviert. Bot wird neu gestartet …"),
    "handlers_run_local_bot_api_install_1": ("⏳ Checking build dependencies…", "⏳ Перевіряю залежності для збирання…", "⏳ Құрастыру тәуелділіктерін тексеріп жатырмын…", "⏳ Build-Abhängigkeiten werden geprüft …"),
    "handlers_run_local_bot_api_install_2": ("⏳ Building the local Bot API server (this may take several minutes)…", "⏳ Збираю локальний сервер Bot API (це може тривати кілька хвилин)…", "⏳ Жергілікті Bot API серверін құрастырып жатырмын (бірнеше минут кетуі мүмкін)…", "⏳ Lokaler Bot-API-Server wird gebaut (das kann einige Minuten dauern) …"),
    "handlers_run_local_bot_api_install_3": ("⏳ Installing the local Bot API server…", "⏳ Встановлюю локальний сервер Bot API…", "⏳ Жергілікті Bot API серверін орнатып жатырмын…", "⏳ Lokaler Bot-API-Server wird installiert …"),
    "handlers_run_local_bot_api_install_4": ("⏳ Local server is ready; switching the bot over…", "⏳ Локальний сервер готовий; перемикаю бота…", "⏳ Жергілікті сервер дайын; ботты ауыстырып жатырмын…", "⏳ Lokaler Server ist bereit; Bot wird umgestellt …"),
    "handlers_run_local_bot_api_install_5": ("⏳ Preparing the local Bot API server…", "⏳ Готую локальний сервер Bot API…", "⏳ Жергілікті Bot API серверін дайындап жатырмын…", "⏳ Lokaler Bot-API-Server wird vorbereitet …"),
    "handlers_run_local_bot_api_install_6": ("⏳ Using the already configured local server…", "⏳ Використовую вже налаштований локальний сервер…", "⏳ Бұрын бапталған жергілікті серверді пайдаланып жатырмын…", "⏳ Bereits konfigurierter lokaler Server wird verwendet …"),
    "handlers_run_local_bot_api_install_7": ("installer failed", "інсталятор завершився з помилкою", "орнатушы сәтсіз аяқталды", "Installationsprogramm fehlgeschlagen"),
    "handlers_run_local_bot_api_install_8": ("installer did not report the local server address", "інсталятор не повідомив адресу локального сервера", "орнатушы жергілікті сервер мекенжайын хабарламады", "Installationsprogramm hat keine lokale Serveradresse gemeldet"),
    "handlers_run_local_bot_api_install_9": ("switch failed", "перемикання завершилося з помилкою", "ауыстыру сәтсіз аяқталды", "Umstellung fehlgeschlagen"),
    "handlers_start_local_bot_api_install_1": ("build dependencies are missing; run scripts/install-local-bot-api.sh manually.", "бракує залежностей для збирання; запусти scripts/install-local-bot-api.sh вручну.", "құрастыру тәуелділіктері жетіспейді; scripts/install-local-bot-api.sh скриптін қолмен іске қос.", "Build-Abhängigkeiten fehlen; führe scripts/install-local-bot-api.sh manuell aus."),
    "handlers_handle_local_bot_api_setup_reply_1": ("Local Bot API installation is already running; wait for it to finish.", "Встановлення локального Bot API вже триває; дочекайся завершення.", "Жергілікті Bot API орнатылып жатыр; аяқталғанша күт.", "Die Installation der lokalen Bot API läuft bereits; warte auf ihren Abschluss."),
    "handlers_handle_local_bot_api_setup_reply_2": ("Send api_id.", "Надішли api_id.", "api_id жібер.", "Sende api_id."),
    "handlers_handle_local_bot_api_setup_reply_3": ("All right. Restarting the bot to apply the update…", "Гаразд. Перезапускаю бота, щоб застосувати оновлення…", "Жарайды. Жаңартуды қолдану үшін ботты қайта іске қосамын…", "In Ordnung. Bot wird neu gestartet, um die Aktualisierung anzuwenden …"),
    "handlers_handle_local_bot_api_setup_reply_4": ("Send api_id (digits only).", "Надішли api_id (лише цифри).", "api_id жібер (тек цифрлар).", "Sende api_id (nur Ziffern)."),
    "handlers_handle_local_bot_api_setup_reply_5": ("Send api_hash.", "Надішли api_hash.", "api_hash жібер.", "Sende api_hash."),
    "handlers_handle_local_bot_api_setup_reply_6": ("Send a non-empty api_hash.", "Надішли непорожній api_hash.", "Бос емес api_hash жібер.", "Sende einen nicht leeren api_hash."),
    "bridge_restart_watcher_loop_1": ("❌ SERVICE_NAME is not set; cannot restart.", "❌ SERVICE_NAME не задано; перезапуск неможливий.", "❌ SERVICE_NAME орнатылмаған; қайта іске қосу мүмкін емес.", "❌ SERVICE_NAME ist nicht gesetzt; Neustart unmöglich."),
    "bridge_restart_watcher_loop_2": ("🔄 Restarting; please wait until the process finishes…", "🔄 Перезапуск триває; зачекай на завершення процесу…", "🔄 Қайта іске қосылуда; процесс аяқталғанша күт…", "🔄 Neustart läuft; bitte warte, bis der Vorgang abgeschlossen ist …"),
    "bridge_restart_watcher_loop_3": ("exit code {value0}", "код завершення {value0}", "шығу коды {value0}", "Exit-Code {value0}"),
    "bridge_restart_watcher_loop_4": ("❌ Restart failed: {value0}", "❌ Перезапуск не вдався: {value0}", "❌ Қайта іске қосу сәтсіз болды: {value0}", "❌ Neustart fehlgeschlagen: {value0}"),
    "bridge_main_1": ("✅ Restart complete; bot is ready.", "✅ Перезапуск завершено; бот готовий до роботи.", "✅ Қайта іске қосу аяқталды; бот дайын.", "✅ Neustart abgeschlossen; Bot ist bereit."),
    "state_store_add_usage_1": ("⚠️ API-equivalent cost for this session rose by another ${value0:.0f} (total ~${value1:.2f}). Consider /compact or /new.", "⚠️ Вартість цього сеансу за еквівалентним тарифом API зросла ще на ${value0:.0f} (разом ~${value1:.2f}). Спробуй /compact або /new.", "⚠️ Осы сеанстың балама API құны тағы ${value0:.0f} өсті (барлығы ~${value1:.2f}). /compact немесе /new қолдан.", "⚠️ Die API-äquivalenten Kosten dieser Sitzung sind um weitere ${value0:.0f} gestiegen (insgesamt ~${value1:.2f}). Erwäge /compact oder /new."),
    "state_store_fetch_account_limits_1": ("(could not retrieve limits: {value0})", "(не вдалося отримати ліміти: {value0})", "(лимиттерді алу мүмкін болмады: {value0})", "(Limits konnten nicht abgerufen werden: {value0})"),
    "state_store_fetch_account_limits_2": ("(no data)", "(немає даних)", "(дерек жоқ)", "(keine Daten)"),
    "bridge_external_request_watcher_loop_1": ("Malformed delegation request.", "Пошкоджений запит делегування.", "Делегирлеу сұрауы қате.", "Beschädigte Delegierungsanfrage."),
    "bridge_external_request_watcher_loop_2": ("Empty task text.", "Порожній текст завдання.", "Тапсырма мәтіні бос.", "Leerer Aufgabentext."),
    "bridge_cross_delegate_watcher_loop_1": ("Rejected: malformed delegation request.", "Відхилено: некоректний формат запиту делегування.", "Қабылданбады: делегирлеу сұрауының пішімі қате.", "Abgelehnt: ungültiges Format der Delegierungsanfrage."),
    "bridge_cross_delegate_watcher_loop_2": ("Rejected: empty task text.", "Відхилено: порожній текст завдання.", "Қабылданбады: тапсырма мәтіні бос.", "Abgelehnt: leerer Aufgabentext."),
    "bridge_cross_delegate_watcher_loop_3": ("Rejected: this Telegram ID is not on the Claude bridge allowlist.", "Відхилено: цього Telegram ID немає в списку дозволених Claude bridge.", "Қабылданбады: бұл Telegram ID Claude көпірінің рұқсат тізімінде жоқ.", "Abgelehnt: Diese Telegram-ID steht nicht auf der Freigabeliste der Claude-Bridge."),
    "bridge_cross_delegate_watcher_loop_4": ("Rejected: the Claude account for this Telegram ID is not ready. Complete /login in the Claude bridge first.", "Відхилено: акаунт Claude для цього Telegram ID не готовий. Спочатку заверши /login у Claude bridge.", "Қабылданбады: бұл Telegram ID үшін Claude аккаунты дайын емес. Алдымен Claude көпірінде /login аяқта.", "Abgelehnt: Das Claude-Konto für diese Telegram-ID ist nicht bereit. Schließe zuerst /login in der Claude-Bridge ab."),
    "bridge_cross_delegate_watcher_loop_5": ("Accepted: Claude bridge started the task. The result will arrive in this Telegram chat from Claude bridge.", "Прийнято: Claude bridge запустив завдання. Результат надійде в цей Telegram-чат від Claude bridge.", "Қабылданды: Claude көпірі тапсырманы бастады. Нәтиже осы Telegram чатына келеді.", "Angenommen: Die Claude-Bridge hat die Aufgabe gestartet. Das Ergebnis kommt in diesen Telegram-Chat."),
    "bridge_cross_delegate_watcher_loop_6": ("Rejected: a previous delegated task is still running.", "Відхилено: попереднє делеговане завдання ще виконується.", "Қабылданбады: алдыңғы делегирленген тапсырма әлі орындалуда.", "Abgelehnt: Eine vorherige delegierte Aufgabe läuft noch."),
    "bridge_process_message_9": ("Voice messages cannot be transcribed: faster-whisper is not installed here (see setup.sh). Send text instead.", "Голосові повідомлення не розпізнаються: тут не встановлено faster-whisper (див. setup.sh). Напиши текстом.", "Дауыс хабарламалары танылмайды: мұнда faster-whisper орнатылмаған (setup.sh қара). Мәтінмен жібер.", "Sprachnachrichten können nicht transkribiert werden: faster-whisper ist hier nicht installiert (siehe setup.sh). Bitte als Text senden."),
    "bridge_process_message_10": ("📥 Downloading attachment…", "📥 Завантажую вкладення…", "📥 Тіркемені жүктеп жатырмын…", "📥 Anhang wird heruntergeladen …"),
    "bridge_process_message_11": ("Could not transcribe the voice message.", "Не вдалося розпізнати голосове повідомлення.", "Дауыс хабарламасын тану мүмкін болмады.", "Sprachnachricht konnte nicht transkribiert werden."),
    "bridge_process_message_12": ("Bridge error:\n\x60\x60\x60\n{value0}\n\x60\x60\x60", "Помилка моста:\n\x60\x60\x60\n{value0}\n\x60\x60\x60", "Көпір қатесі:\n\x60\x60\x60\n{value0}\n\x60\x60\x60", "Bridge-Fehler:\n\x60\x60\x60\n{value0}\n\x60\x60\x60"),
    "runtime_module_1": ("🔄 Bot is restarting; resend your message in a minute.", "🔄 Бот перезапускається; повтори повідомлення за хвилину.", "🔄 Бот қайта іске қосылуда; хабарламаны бір минуттан кейін қайтала.", "🔄 Bot wird neu gestartet; sende deine Nachricht in einer Minute erneut."),
    "language_command_description": ("Choose interface and persona language", "Вибрати мову інтерфейсу й персони", "Интерфейс пен персона тілін таңдау", "Sprache für Oberfläche und Persona wählen"),
    "bridge_file_send_watcher_loop_1": ("Rejected: malformed file-send request.", "Відхилено: пошкоджений запит на надсилання файлу.", "Қабылданбады: файл жіберу сұрауы қате.", "Abgelehnt: beschädigte Dateisendeanfrage."),
    "bridge_file_send_watcher_loop_2": ("Rejected: invalid Telegram chat_id.", "Відхилено: некоректний Telegram chat_id.", "Қабылданбады: Telegram chat_id қате.", "Abgelehnt: ungültige Telegram-chat_id."),
    "bridge_file_send_watcher_loop_3": ("Rejected: Telegram ID is not on the Claude bridge allowlist.", "Відхилено: Telegram ID немає в списку дозволених Claude bridge.", "Қабылданбады: Telegram ID Claude көпірінің рұқсат тізімінде жоқ.", "Abgelehnt: Telegram-ID steht nicht auf der Freigabeliste der Claude-Bridge."),
    "bridge_file_send_watcher_loop_4": ("Rejected: invalid path or caption.", "Відхилено: некоректний шлях або підпис.", "Қабылданбады: жол немесе сипаттама қате.", "Abgelehnt: ungültiger Pfad oder Untertitel."),
    "bridge_file_send_watcher_loop_5": ("Rejected: caption exceeds Telegram's limit.", "Відхилено: підпис перевищує ліміт Telegram.", "Қабылданбады: сипаттама Telegram шегінен асады.", "Abgelehnt: Untertitel überschreitet das Telegram-Limit."),
    "bridge_file_send_watcher_loop_6": ("Rejected: file must be a regular file inside CLAUDE_TELEGRAM_OUTBOX.", "Відхилено: файл має бути звичайним файлом у CLAUDE_TELEGRAM_OUTBOX.", "Қабылданбады: файл CLAUDE_TELEGRAM_OUTBOX ішіндегі кәдімгі файл болуы керек.", "Abgelehnt: Datei muss eine reguläre Datei in CLAUDE_TELEGRAM_OUTBOX sein."),
    "bridge_file_send_watcher_loop_7": ("Rejected: file exceeds {value0} bytes.", "Відхилено: файл перевищує {value0} байтів.", "Қабылданбады: файл көлемі {value0} байттан асады.", "Abgelehnt: Datei überschreitet {value0} Byte."),
    "bridge_file_send_watcher_loop_8": ("File “{value0}” sent to Telegram.", "Файл «{value0}» надіслано в Telegram.", "«{value0}» файлы Telegram-ға жіберілді.", "Datei „{value0}“ an Telegram gesendet."),
    "bridge_file_send_watcher_loop_9": ("Telegram rejected the file: ", "Telegram не прийняв файл: ", "Telegram файлды қабылдамады: ", "Telegram hat die Datei abgelehnt: "),
    "telegram_api_send_attachment_1": ("File \x60{value0}\x60 is too large to send ({value1} bytes).", "Файл \x60{value0}\x60 завеликий для надсилання ({value1} байтів).", "\x60{value0}\x60 файлы жіберуге тым үлкен ({value1} байт).", "Datei \x60{value0}\x60 ist zu groß zum Senden ({value1} Byte)."),
    "telegram_api_send_attachment_2": ("Could not send \x60{value0}\x60: {value1}", "Не вдалося надіслати \x60{value0}\x60: {value1}", "\x60{value0}\x60 жіберілмеді: {value1}", "\x60{value0}\x60 konnte nicht gesendet werden: {value1}"),
    "telegram_api_download_error_from_exception_1": ("File not downloaded: Telegram took too long to prepare it. Try again or send a link.", "Файл не завантажено: Telegram надто довго його готував. Спробуй ще раз або надішли посилання.", "Файл жүктелмеді: Telegram оны тым ұзақ дайындады. Қайтала немесе сілтеме жібер.", "Datei nicht heruntergeladen: Telegram hat sie zu lange vorbereitet. Versuche es erneut oder sende einen Link."),
    "telegram_api_download_error_from_exception_2": ("File not downloaded: no access to the local Bot API file.", "Файл не завантажено: немає доступу до файлу локального Bot API.", "Файл жүктелмеді: жергілікті Bot API файлына қолжетім жоқ.", "Datei nicht heruntergeladen: kein Zugriff auf die lokale Bot-API-Datei."),
    "telegram_api_download_error_from_exception_3": ("File not downloaded: Telegram connection error. Try again or send a link.", "Файл не завантажено: помилка зв’язку з Telegram. Спробуй ще раз або надішли посилання.", "Файл жүктелмеді: Telegram байланыс қатесі. Қайтала немесе сілтеме жібер.", "Datei nicht heruntergeladen: Verbindungsfehler zu Telegram. Versuche es erneut oder sende einen Link."),
    "telegram_api_download_error_from_exception_4": ("File not downloaded: Telegram did not provide it. Try again or send a link.", "Файл не завантажено: Telegram його не надав. Спробуй ще раз або надішли посилання.", "Файл жүктелмеді: Telegram оны бермеді. Қайтала немесе сілтеме жібер.", "Datei nicht heruntergeladen: Telegram hat sie nicht bereitgestellt. Versuche es erneut oder sende einen Link."),
    "telegram_api_get_file_error_1": ("File not downloaded: it exceeds Telegram's 20 MB cloud limit. Enable the local Bot API or send a link.", "Файл не завантажено: перевищено хмарний ліміт Telegram у 20 МБ. Увімкни локальний Bot API або надішли посилання.", "Файл жүктелмеді: Telegram-ның 20 МБ бұлт шегінен асады. Жергілікті Bot API қос немесе сілтеме жібер.", "Datei nicht heruntergeladen: Sie überschreitet Telegrams Cloud-Limit von 20 MB. Aktiviere die lokale Bot API oder sende einen Link."),
    "telegram_api_get_file_error_2": ("File not downloaded: Telegram refused to provide it. Resend it or send a link.", "Файл не завантажено: Telegram відмовив у видачі. Надішли його знову або дай посилання.", "Файл жүктелмеді: Telegram беруден бас тартты. Қайта жібер немесе сілтеме бер.", "Datei nicht heruntergeladen: Telegram hat die Bereitstellung verweigert. Sende sie erneut oder gib einen Link."),
    "telegram_api_download_telegram_file_1": ("File not downloaded: Telegram did not return a file path. Try again or send a link.", "Файл не завантажено: Telegram не повернув шлях до файлу. Спробуй ще раз або надішли посилання.", "Файл жүктелмеді: Telegram файл жолын қайтармады. Қайтала немесе сілтеме жібер.", "Datei nicht heruntergeladen: Telegram hat keinen Dateipfad zurückgegeben. Versuche es erneut oder sende einen Link."),
    "telegram_api_download_telegram_file_2": ("File not downloaded: the local Bot API can no longer find it. Resend it or send a link.", "Файл не завантажено: локальний Bot API більше його не бачить. Надішли знову або дай посилання.", "Файл жүктелмеді: жергілікті Bot API оны енді көрмейді. Қайта жібер немесе сілтеме бер.", "Datei nicht heruntergeladen: Die lokale Bot API findet sie nicht mehr. Sende sie erneut oder gib einen Link."),
    "telegram_api_download_telegram_file_3": ("File not downloaded: local Bot API path is not an accessible file.", "Файл не завантажено: шлях локального Bot API не вказує на доступний файл.", "Файл жүктелмеді: жергілікті Bot API жолы қолжетімді файл емес.", "Datei nicht heruntergeladen: Der lokale Bot-API-Pfad ist keine zugängliche Datei."),
    "telegram_api_download_telegram_file_4": ("File not downloaded: size exceeds the allowed limit.", "Файл не завантажено: перевищено дозволений розмір.", "Файл жүктелмеді: көлемі рұқсат етілген шектен асады.", "Datei nicht heruntergeladen: Größe überschreitet das erlaubte Limit."),
    "chat_process_chat_reader_loop_5": ("{value0} (empty)", "{value0} (порожньо)", "{value0} (бос)", "{value0} (leer)"),
    "chat_process_chat_reader_loop_6": ("Error", "Помилка", "Қате", "Fehler"),
    "chat_process_chat_reader_loop_7": ("Result", "Результат", "Нәтиже", "Ergebnis"),
    "chat_process_deliver_pending_final_1": ("⚠️ Telegram has not accepted the reply yet; retrying delivery:\n\n", "⚠️ Telegram поки не прийняв відповідь; повторюю надсилання:\n\n", "⚠️ Telegram жауапты әлі қабылдамады; жіберуді қайталап жатырмын:\n\n", "⚠️ Telegram hat die Antwort noch nicht angenommen; Zustellung wird wiederholt:\n\n"),
    "chat_process_deliver_turn_result_1": ("…and {value0} more steps above…", "…і ще {value0} кроків вище…", "…жоғарыда тағы {value0} қадам…", "…und {value0} weitere Schritte oben …"),
    "chat_process_deliver_turn_result_2": ("<details><summary>🔧 Process ({value0})</summary>\n{value1}\n</details>", "<details><summary>🔧 Процес ({value0})</summary>\n{value1}\n</details>", "<details><summary>🔧 Процесс ({value0})</summary>\n{value1}\n</details>", "<details><summary>🔧 Ablauf ({value0})</summary>\n{value1}\n</details>"),
    "chat_process_deliver_turn_result_3": ("⏹ Turn interrupted; the process ended before replying.", "⏹ Хід перервано: процес завершився, не дочекавшись відповіді.", "⏹ Жауап келмей тұрып процесс аяқталып, жауап үзілді.", "⏹ Durchlauf unterbrochen; der Prozess endete vor der Antwort."),
    "chat_process_deliver_turn_result_4": ("(no reply; see process above)", "(немає відповіді; дивись процес вище)", "(жауап жоқ; жоғарыдағы процесті қара)", "(keine Antwort; siehe Ablauf oben)"),
    "chat_process_deliver_turn_result_5": ("(empty)", "(порожньо)", "(бос)", "(leer)"),
    "chat_process_deliver_turn_result_6": ("🚫 **Blocked** (approval required):", "🚫 **Заблоковано** (потрібен дозвіл):", "🚫 **Бұғатталды** (рұқсат қажет):", "🚫 **Blockiert** (Genehmigung erforderlich):"),
    "chat_process_deliver_turn_result_7": ("/approve — retry once with bypass", "/approve — повторити один раз із bypass", "/approve — bypass арқылы бір рет қайталау", "/approve — einmal mit Bypass wiederholen"),
    "chat_process_deliver_turn_result_8": ("/approve session — enable bypass for this session", "/approve session — увімкнути bypass для цього сеансу", "/approve session — осы сеанс үшін bypass қосу", "/approve session — Bypass für diese Sitzung aktivieren"),
    "chat_process_deliver_turn_result_9": ("/deny — leave it blocked", "/deny — залишити заблокованим", "/deny — бұғатталған күйде қалдыру", "/deny — blockiert lassen"),
    "chat_process_finish_delivery_1": ("⚠️ Could not deliver the reply to Telegram:\n\n", "⚠️ Не вдалося доставити відповідь у Telegram:\n\n", "⚠️ Жауапты Telegram-ға жеткізу мүмкін болмады:\n\n", "⚠️ Antwort konnte nicht an Telegram zugestellt werden:\n\n"),
    "chat_process_flush_draft_1": ("Thinking", "Думаю", "Ойланып жатырмын", "Denke nach"),
    "chat_process_format_turn_footer_1": ("Tokens: {value0}", "Токени: {value0}", "Токендер: {value0}", "Tokens: {value0}"),
    "chat_process_format_turn_footer_2": ("Your session ID (before delegation): \x60{value0}\x60. Resume delegated session: \x60/resume {value1}\x60", "Твій ID сеансу (до делегування): \x60{value0}\x60. Продовжити делегований сеанс: \x60/resume {value1}\x60", "Сенің сеанс ID-ің (делегирлеуге дейін): \x60{value0}\x60. Делегирленген сеансты жалғастыру: \x60/resume {value1}\x60", "Deine Sitzungs-ID (vor der Delegierung): \x60{value0}\x60. Delegierte Sitzung fortsetzen: \x60/resume {value1}\x60"),
    "chat_process_format_turn_footer_3": ("Resume delegated session: \x60/resume {value0}\x60", "Продовжити делегований сеанс: \x60/resume {value0}\x60", "Делегирленген сеансты жалғастыру: \x60/resume {value0}\x60", "Delegierte Sitzung fortsetzen: \x60/resume {value0}\x60"),
    "handlers_send_whitelist_prompt_1": ("You are not on the allowlist.\nYour Telegram ID: \x60{value0}\x60\n\nAdd it to the configuration, separated by commas, then tap the button below:", "Тебе немає в списку дозволених.\nТвій Telegram ID: \x60{value0}\x60\n\nДодай його до конфігурації через кому й натисни кнопку нижче:", "Сен рұқсат тізімінде жоқсың.\nTelegram ID: \x60{value0}\x60\n\nОны конфигурацияға үтір арқылы қосып, төмендегі түймені бас:", "Du stehst nicht auf der Freigabeliste.\nDeine Telegram-ID: \x60{value0}\x60\n\nFüge sie kommasepariert zur Konfiguration hinzu und tippe dann auf die Schaltfläche unten:"),
    "handlers_send_whitelist_prompt_2": ("Done ✅", "Готово ✅", "Дайын ✅", "Erledigt ✅"),
    "handlers_start_delegate_turn_1": ("The previous delegated task is still running.", "Попереднє делеговане завдання ще виконується.", "Алдыңғы делегирленген тапсырма әлі орындалуда.", "Die vorherige delegierte Aufgabe läuft noch."),
    "handlers_start_delegate_turn_2": ("Delegated Claude account is not connected. Use /login delegate.", "Делегований акаунт Claude не підключено. Використай /login delegate.", "Делегирленген Claude аккаунты қосылмаған. /login delegate қолдан.", "Das delegierte Claude-Konto ist nicht verbunden. Verwende /login delegate."),
    "handlers_start_delegate_turn_3": ("Cannot use --env together with --resume.", "Не можна використовувати --env разом із --resume.", "--env пен --resume бірге қолданылмайды.", "--env und --resume können nicht gemeinsam verwendet werden."),
    "handlers_start_delegate_turn_4": ("Cannot resume this delegation: resume_session_id does not match the delegator's latest session.", "Не можна продовжити делегування: resume_session_id не збігається з останнім сеансом делегатора.", "Бұл делегирлеуді жалғастыру мүмкін емес: resume_session_id делегатордың соңғы сеансына сәйкес келмейді.", "Diese Delegierung kann nicht fortgesetzt werden: resume_session_id stimmt nicht mit der letzten Sitzung des Delegierenden überein."),
    "handlers_start_delegate_turn_5": ("Delegated task was not started.", "Делеговане завдання не запущено.", "Делегирленген тапсырма басталмады.", "Delegierte Aufgabe wurde nicht gestartet."),
}
for _key, _values in _COMMAND_OUTPUTS.items():
    for _language, _value in zip(("en", "uk", "kk", "de"), _values):
        STRINGS[_language][_key] = _value


def t(key, lang=None, **kwargs) -> str:
    lang = lang or current_language.get()
    template = STRINGS.get(lang, {}).get(key)
    if template is None:
        template = STRINGS["ru"][key]
    return template.format(**kwargs)
